probot/probot

- README.md
Add @parkr's auto-reply (@jekyllbot) to the list of other GitHub flow bots.
> Add @parkr's Auto-reply

- lib/actions/assign.js
- lib/actions/comment.js
- lib/actions/label.js
- lib/actions/lock.js
- lib/actions/unlabel.js
- lib/actions/unlock.js
- lib/dispatcher.js
- lib/payload.js
- test/actions/assign.js
- test/actions/comment.js
- test/actions/label.js
- test/actions/unlabel.js
This removes some duplication in the actions.
> Add Payload class

- CONTRIBUTING.md
- server.js
…and update development password to actually be what is in the docs.
Fixes #24
> Fix contributing docs

- lib/actions.js
- lib/actions/react.js
- package.json
- server.js
No tests yet but feedback appreciated.
cc/ @bkeepers
> Add support for reactions

- README.md
I'll be hanging out in the Gitter.im chat room if anyone has any questions or wants help with anything.
https://gitter.im/bkeepers/PRobot
> Add Gitter.im badge

- lib/actions.js
- lib/actions/unassign.js
- package.json
- test/actions/unassign.js
```yml
- then:
unassign: bkeeepers
unassign: [bkeeepers, benbalter]
```
Currently blocked by https://github.com/mikedeboer/node-github/issues/431#issuecomment-252762465
> Add unassign action

- lib/actions/react.js
- lib/configuration.js
- package.json
- server.js
@bkeepers Did you mean something like this for #33 ?
> Verbose logging

- README.md
- docs/configuration.md
- docs/examples.md
This updates the README and configuration docs to reflect reality.
> Update docs to reflect reality

- lib/configuration.js
- lib/parser.js
- lib/parser.pegjs
- package.json
- test/conditions.js
- test/parser.js
> Use pegjs-util

- CONTRIBUTING.md
> Add docs on implementing actions and conditions

- lib/actions/assign.js
- lib/actions/label.js
- lib/actions/unassign.js
- lib/actions/unlabel.js
- lib/parser.pegjs
- lib/transformer.js
- test/actions/assign.js
- test/actions/unassign.js
- test/actions/unlabel.js
- test/parser.js
This just cleans up some quirks and ugliness with the parser.
> Refactor parser

- lib/configuration.js
- lib/sandbox.js
This is just a minor refactor that makes it so all the code for executing the configuration is isolated to the Sandbox class
> Move vm code into sandbox

- lib/configuration.js
- lib/dispatcher.js
- lib/workflow.js
- test/configuration.js
- test/workflow.js
Minor refactoring to move logic for deciding which workflows to execute into the workflow.
> Move logic for filtering workflows

- CONTRIBUTING.md
- script/simulate
- script/tunnel
A few scripts to make things easier.
> Add script/simulate and script/tunnel

- lib/context.js
- test/context.js
- test/fixtures/webhook/push.json
The push event is missing `repository.owner.login`, but provides the login as `repository.owner.name`.
> Fix error on push event

- lib/context.js
- lib/payload.js
This removes the payload module, which no longer has any behavior.
> Remove payload module

- .env.example
- .travis.yml
- index.js
- package.json
- script/bootstrap
> Use dotenv-safe

- index.js
- package.json
Eventually this should be extensible so people can use whatever method they want for error reporting.
> Add raven to report errors to sentry

- docs/best-practices.md
Starting to write down some conventions that are emerging.
@lee-dohm @MarshallOfsound @sridharavinash Anything else to add?
cc #100
> Start documenting best practices

- bin/probot
```
$ probot run
Node.js version ~7.7.0 is required. You have v4.4.7.
```
cc @jbjonesjr
> Ensure node version is satisfied

- index.js
- lib/robot.js
- package.json
- test/robot.js
This moves the logger setup to `index.js` and adds a stream to the logger for Sentry so `robot.log.error` gets reported.
> Logs to Sentry

- bin/probot-run.js
- bin/probot.js
- package.json
- add missing `semver` dependency
- lint files in `bin/`
- ignore `localtunnel` issue for now
> add .js ext to files in bin/; closes #129

- docs/best-practices.md
This adds the [Three Laws of Robotics](https://en.wikipedia.org/wiki/Three_Laws_of_Robotics) and a section on empathy to the best practices doc.
Closes #100
> Add three laws & empathy

- lib/private-key.js
- test/private-key.js
this will allow us to run probot apps safely on glitch.com
> allow to set PRIVATE_KEY with "\\n" characters

- docs/deployment.md
This PR adds a last step to the Heroku development guide explaining how to verify that the plugin is running and receiving webhooks.
> document tailing logs on heroku

- bin/probot-simulate.js
- docs/plugins.md
- index.js
- lib/plugin.js
- lib/robot.js
- lib/server.js
- package-lock.json
- package.json
- test/fixtures/example.js
- test/index.js
- test/plugins.js
- test/server.js
Iterating on the discussion in #180, this uses express for the server, and allows plugins to add routes.
cc @anglinb
Closes #107
> Use Express for the web server and allow plugins add routes

- index.js
- lib/robot.js
- test/robot.js
This adds some fields from the event to the error log so it's easier to debug what event caused the error.
> Log the event with errors to aid debugging

- lib/robot.js
...to 1 min less than GitHub expiry.
Probably fixes https://github.com/probot/stale/issues/53
> Reduce auth token ttl

- docs/plugins.md
Adds more testing documentation and recommended practices! Any feedback even on wording is welcome, but esp on fact checking the content would be great!
Fixes https://github.com/probot/friction/issues/3
> add recommended testing documentation

- bin/probot-run.js
- bin/probot-simulate.js
- bin/probot.js
- index.js
- lib/context.js
- lib/paginate.js
- lib/plugin.js
- lib/private-key.js
- lib/robot.js
- lib/serializers.js
- lib/server.js
- lib/tunnel.js
- package-lock.json
- package.json
- test/context.js
- test/fixtures/example.js
- test/index.js
- test/plugins.js
- test/private-key.js
- test/robot.js
- test/serializers.js
- test/server.js
> STANDARD LINT ALL OF THE THINGS

- CHANGELOG.md
- index.js
- lib/robot.js
- package-lock.json
- package.json
- test/index.js
- test/robot.js
Update changelog and prepare for 0.10.0 release.
> Release 0.10.0

- docs/README.md
Fixes a few broken links
/cc @probot/maintainers
> Fix doc links

- app.json
- docs/development.md
- index.js
makes our use of Probot capitalization consistent.
not sure if this will break any of our other set up that depends on `app.json` ?
> pro the bot

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- test/index.js
Pushing out a new release with an updated  node-github client.
> Release 0.11

- docs/deployment.md
> deployment: typo

- docs/deployment.md
> deployment: Glitch

- docs/deployment.md
> tiny glitch fixes

- docs/pagination.md
`robot.console` doesn't exist.
> docs: fix log statement

- CONTRIBUTING.md
- package-lock.json
> Changes made in CONTRIBUTING.md according to #271

- README.md
> Added NPM version badge to readme.

- docs/development.md
https://github.com/probot/create-probot-app/issues/11
> Update output mentioned in 'Generating a new app' section

- .travis.yml
- package.json
Because @gr2m won't leave me alone about it.
> Setup semantic-release

- package.json
to avoid problems like this: https://travis-ci.org/probot/probot/builds/287910643#L1696
> run docs script after semantic release

- .gitignore
- .travis.yml
> Add package-lock.json to gitignore

- docs/hello-world.md
Following up on #294, this adds the list of ideas to the hello world example in case people are looking for inspiration while they're learning about Probot.
> Add list of ideas to hello world example

- docs/testing.md
This PR addresses a minor typo with a missing "is".
> Minor typo fix

- docs/best-practices.md
See: https://en.wikipedia.org/w/index.php?title=Three_Laws_of_Robotics#Zeroth_Law_added
> Add the zeroth law of robotics

- README.md
- appveyor.yml
Closes #312 by setting up and configuring AppVeyor.
> Setup Appveyor

- docs/development.md
- docs/hello-world.md
Created a Glitch project with instructions for setting up a new Probot development to make it easier for new users.
Closes #241
> Add option to develop Probot on Glitch

- lib/index.js
- package.json
I meant to do this months ago and it's been annoying me lately.
> Move index.js into lib/

- docs/logging.md
- docs/testing.md
This adds some docs on logging in a Probot app.
cc #320
> Docs on logging

- bin/probot-run.js
- lib/robot.js
This Pull Request makes two changes to the module:
- The first updates the argument order used when running probot. This doesn't have any technical impact on the application, but it does make the arguments easier to manage and organize. I notice this when working on https://github.com/pholleran-org/probot/pull/1/ (oauth support), and the annoyance when auth arguments were interspersed with other arguments. 
- The second updates some styling of comments in `robot.js`. This is currently inconsistent in how the styling is currently applied, and standardizes the file for the block comment opening flush and all subsequent lines to be indented one space.
I wanted to break these changes out so they don't complicate the oauth implementation PR.
> General cleanup

- package.json
> fix(package): update jest to version 22.0.3

- docs/deployment.md
I am just wondering why don't you use marketplace link?
> [Suggestion] Use marketplace link instread of original link

- docs/hello-world.md
New Developers may not not understand how to install node and probot with the current instructions. This PR expands the instructions for developers working on Mac OS X.
> How to install Node and Probot for Development

- docs/hello-world.md
When you click the "Remix on Glitch" button in the [Getting Started | Hello World guide](https://probot.github.io/docs/hello-world/), the link will load forever. So, I updated the link in this patch 😄
> Update "Remix on Glitch" button link

- docs/pagination.md
- lib/github.js
- test/github.test.js
Fixes https://github.com/probot/probot/issues/317
> Add early termination to paginate method

- lib/index.js
change the `loger.trace` to `loger.info` as specified in the issue Update log when server starts  #349. 😄
> update log when server starts #394

- CONTRIBUTING.md
This search will find repositories that have the topic of `probot` or `probot-app` that have at least one issue labeled `good-first-issue`. They'll have to dig in from there, but this should be a good start at least :+1:
> Add section on how to help if you're just starting out

- docs/simulating-webhooks.md
Heya folks, I've tweaked the `probot simulate` docs a bit based on @kytrinyx's ✨ feedback in #404 (👻). I didn't make any major changes, but I'd be interested in hearing if y'all think that it would be a good idea to add more details.
Closes #404
> Simulate docs

- lib/github.js
- package.json
- script/console
- test/plugins/stats.test.js
> migrate to @octokit/rest

- docs/development.md
This updates the docs to use `npx` and adds docs for `yarn create`
Closes https://github.com/probot/create-probot-app/pull/18
> Use npx, document yarn

- docs/deployment.md
Fixes issue https://github.com/probot/probot/issues/420
> Update docs about glitch deployment

- docs/summer-of-code.md
During our office hours last week, @gr2m and I chatted about the need for a centralized place for Summer-of-Code related questions.
I think this is all pretty straightforward; my only concern is if y'all want your names and faces in the **Mentors** part. I do think its important that we be clear about who is and isn't a mentor (especially in these early days of people asking a ton of questions), but if it makes anyone uncomfortable feel free to let me know!
cc @bkeepers @tcbyrd @gr2m
> Summer of Code doc

- docs/github-api.md
- docs/persistence.md
- lib/github.js
Fix a few references to node-github in the docs.
cc #400
> Update node-github => octokit/rest.js in docs

- docs/development.md
- lib/private-key.js
- test/private-key.test.js
> Fix: fail if there are several .pem files

- docs/deployment.md
A lot of people are building awesome apps, but not that many are adding them to the website. I'd like to add a couple gentled nudges to people to list their apps.
I'm not sure where all would be the best place to do it, but here's a start.
> Docs: encourage people to add their app to the website

- package.json
> chore(package): update raven to version 2.4.2

- lib/github.js
- lib/github/index.js
- lib/github/logging.js
- lib/github/pagination.js
- lib/github/rate-limiting.js
A few small tweaks to make the setup of the GitHub client extensions a little cleaner in preparation for adding GraphQL support. 😁 
fyi @gr2m
> Refactor GitHub client extensions

- docs/webhooks.md
Mentioned that an event list can also be passed to .on()
> Mentioned that an event list can also be passed to .on()

- docs/development.md
This PR is a companion to https://github.com/probot/template/pull/54 that documents the use of `npm run dev` in the template app.
I also tried to make the wording and capitalization of headings consistent with the rest(ish) of the probot docs (first letter of first word capitalized, all subsequent words lowercase).
> Update dev docs

- docs/deployment.md
Found from failing build in https://github.com/probot/probot.github.io/pull/152
> Correct featured apps link

- CONTRIBUTING.md
- LICENSE
- README.md
- package.json
- test/plugins/__snapshots__/default.test.js.snap
Hey there! These are my changes from #522. 
* 57e5cb7 docs: add keywords, bugs, homepage
* 5876f45 chore: change description to match github
* d360c7a docs: add the github description
* e468973 docs: Change depth of heading for section
* 3e6e2a2 chore: Update the license year
* eaed8f3 fix: change spelling of imma to 'I\'m going to'
I think that covers it. What do you think?
> docs: suggested changes from audit #522

- README.md
See #522 for more in depth conversation.
Suggestions welcome!
> Audit of readme based on maintainer audit feedback

- docs/simulating-webhooks.md
> Trigging -> Triggering a webhook [Docs]

- docs/deployment.md
> Update deployment documentation to now

- src/github/index.ts
- src/github/logging.ts
@octokit/rest [issue 896](https://github.com/octokit/rest.js/issues/896)
> fix DEPRECATED response.meta @octokit/rest

- docs/configuration.md
Glanced at this earlier, and I think the backticks improve readability
> Add backticks in doc

- lib/plugins/stats.js
I created a `v6-release` branch based on `v6.2.0` and this PR backports #566 to that branch so we can cut a release to fix it.
> Backport: Optimize IGNORED_ACCOUNTS check

- README.md
> robot => app

- docs/configuration.md
follow up for https://github.com/probot/probot/pull/577 ping @hiimbex
> Configuration: DISABLE_STATS=true

- package.json
- src/application.ts
- src/context.ts
- src/github-app.ts
- src/github/graphql.ts
- src/github/index.ts
- src/github/logging.ts
- src/github/pagination.ts
- src/github/rate-limiting.ts
- src/index.ts
- src/logger.ts
- src/middleware/log-request-errors.ts
- src/plugins/default.ts
- src/plugins/sentry.ts
- src/plugins/stats.ts
- src/resolver.ts
- src/serializers.ts
- src/server.ts
- src/webhook-proxy.ts
- src/wrap-logger.ts
- tslint.json
Prior to #372, we were using `standard` for linting. I just noticed there's a tslint-config-standard. Most of the changes it makes are minor, but I think it's nice to have consistent code style.
> Use tslint-config-standard

- package.json
7.0 was just published and promoted to `@latest`
> Remove next tag

- docs/development.md
per #600
Thanks to @hiimbex I have been tinkering more with probot and was provided a good-first-issue :)
> update the example app id image

- .github/config.yml
The phrase is "meantime," not "mean time" (which describes time that is mean).
> Fix new contribution grammar

- docs/development.md
It will help people who read docs to understand:
- they can have typescript app as well
- this is how they can generate it
without going through other resources to find out.
> Updating docs: Adding typescript option to npx/yarn command

- test/github/graphql.test.ts
https://github.com/probot/probot/issues/582 Convert tests that `test/github/graphql.test.js`  to TypeScript.
> Convert graphql tests to TypeScript

- package.json
> update @types/node to version 10.7.0

- docs/testing.md
To be inline with changes in https://github.com/probot/probot/pull/626
> Rename event->name in docs

- docs/extensions.md
Adds community created content section to extensions and lists @dessant's app.
> Add probot-messages

- package.json
> update bottleneck to version 2.8.0

- package.json
> update ts-jest to version 23.1.4

- .github/release-drafter.yml
@JasonEtco added the release-drafter app yesterday, but looks like it needs a configuration file before it starts working.
> Add template for release-drafter app

- docs/configuration.md
Tests on the website are failing because of this: https://travis-ci.org/probot/probot.github.io/builds/421240578
> Fix link to deployment docs

- test/server.test.ts
> convert server to TypeScript

- docs/best-practices.md
Just an update to remove duplicate word in a sentence.
> Remove duplicated word

- package.json
> Require @octokit/webhooks@^5.0.2

- src/manifest-creation.ts
- test/fixtures/setup/response.json
- test/manifest-creation.test.js
> httpSSSSSSS

- docs/development.md
- views/setup.hbs
Just noticed these two typos
Should probably update this screenshot as well: https://probot.github.io/docs/development/#configuring-a-github-app
-----
[View rendered docs/development.md](https://github.com/probot/probot/blob/app-manifest-fix-typos/docs/development.md)
> Fix two typos

- test/apps/default.test.ts
> chore(test): convert app/default test to TypeScript

- src/manifest-creation.ts
- test/manifest-creation.test.js
Wrapping the PEM in quotes stops Glitch from spamming error message to the console.
Closes https://github.com/probot/probot/issues/736
> Wrap pem in quotes to make Glitch happy

- package.json
- src/index.ts
- test/index.test.js
Quick fix for an issue introduced in #726.
I'll follow up with tests and proper fix after this is out.
>  Allow starting probot without token or id/cert

- README.md
I've made some design changes to the README, to make the project look a little more loved.
| Before | After |
| --- | --- |
| ![screen shot 2018-10-19 at 16 49 11](https://user-images.githubusercontent.com/10660468/47248391-ec822800-d3be-11e8-9502-28e21cec1a8c.png) | ![screen shot 2018-10-19 at 16 48 13](https://user-images.githubusercontent.com/10660468/47248382-dbd1b200-d3be-11e8-9e7d-1afe61991b4c.png) |
<h3 align="center">👀 📖 <strong><a href="https://github.com/probot/probot/blob/pretty-readme/README.md">View Rendered</a></strong> 📖 👀 </h3>
-----
[View rendered README.md](https://github.com/probot/probot/blob/pretty-readme/README.md)
> Pretty readme

- docs/deployment.md
```diff
- GitHub Actions allows you to trigger workflows based on GitHub events, which makes it a great fit for running Probot Apps. To run a your app on GitHub Actions:
+ GitHub Actions allows you to trigger workflows based on GitHub events, which makes it a great fit for running Probot Apps. To run your app on GitHub Actions:
```
💖
-----
[View rendered docs/deployment.md](https://github.com/yeskunall/probot/blob/patch-1/docs/deployment.md)
> Fix typo in `deployment.md`

- bin/probot-receive.js
Closes https://github.com/probot/probot/issues/747
> Do not require token on probot-receive

- src/private-key.ts
- test/private-key.test.ts
> [FIX] PRIVATE_KEY_PATH error handling (#778)

- docs/configuration.md
- docs/testing.md
- test/application.test.ts
Update occurrences of `recieve` to be `receive`
-----
[View rendered docs/configuration.md](https://github.com/FalconWiz/probot/blob/ahinett/fix/testing-documentation/docs/configuration.md)
[View rendered docs/testing.md](https://github.com/FalconWiz/probot/blob/ahinett/fix/testing-documentation/docs/testing.md)
> Fix misspellings of receive

- docs/serverless-deployment.md
Fix broken link
-----
[View rendered docs/serverless-deployment.md](https://github.com/chadfawcett/probot/blob/patch-1/docs/serverless-deployment.md)
> Fix link to "Create the GitHub App"

- .gitignore
- package-lock.json
Regarding what @JasonEtco mentioned in #769. 
Open to discussion below 😄 
Closes #769
> Added package-lock.json #769

- .travis.yml
Hey 👋 I've removed the allowed failure configuration for node 10, aiming to close #801
> Removed allowed failure configuration for node 10

- LICENSE
This changes the license year to 2019.
Well, happy new year 😄🎉
> fix: Update year to 2019

- .npmrc
- package-lock.json
> remove .npmrc file

- src/@types/@octokit/webhooks/index.d.ts
We want an argument with the type of Options, not an argument named Options with the type of any
> Fix Webhooks class constructor

- src/apps/stats.ts
follow up for https://github.com/probot/probot/pull/775
This will fix the currently breaking builds on master. I wonder how this was not caught by CI 🤔
> GitHubAPI.paginate callback signature in stats

- README.md
-----
[View rendered README.md](https://github.com/probot/probot/blob/gr2m-patch-3/README.md)
> README: fix link to travis

- .travis.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
> semantic-release setup

- CONTRIBUTING.md
- README.md
-----
[View rendered CONTRIBUTING.md](https://github.com/probot/probot/blob/beta-readme/CONTRIBUTING.md)
[View rendered README.md](https://github.com/probot/probot/blob/beta-readme/README.md)
> README / CONTRIBUTING updates for beta releases

- docs/testing.md
-----
[View rendered docs/testing.md](https://github.com/geminicaprograms/probot/blob/patch-1/docs/testing.md)
> Fix typo in 'testing.md'

- bin/probot-run.js
- src/application.ts
- src/index.ts
- test/application.test.ts
- test/index.test.js
> Create only a single redis connection

- test/fixtures/example.ts
- test/fixtures/plugin/stub-plugin.js
- test/fixtures/plugin/stub-plugin.ts
This seems to be the last of the test stuff to convert to TS
> chore(test): Convert fixtures to TS

- src/application.ts
- src/github/index.ts
- src/index.ts
- test/github.test.ts
- test/github/graphql.test.ts
- test/index.test.js
**Feature proposal**
To simplify usage of custom plugins it is sometimes easier to use custom Octokit constructor instead of the provided one. See discussion in #826.
> feat: ability to pass custom Octokit constructor as an option

- src/application.ts
- src/context.ts
> feat: Add overloads for all Webhook events

- src/index.ts
- src/middleware/log-request-errors.ts
- test/__snapshots__/index.test.ts.snap
- test/index.test.ts
~~Requires #849 and #848 and #851 to be merged first~~
This is completely independent from the other PRs. It can be merged whenever
> test: convert final test to TypeScript

- package-lock.json
- package.json
- src/@types/connect-sse/index.d.ts
- src/@types/smee-client/index.d.ts
- src/webhook-proxy.ts
- test/webhook-proxy.test.ts
This is the final test to be converted
Credits goes to #705 for getting the ball rolling on thi
> test: convert webhook proxy test to TS

- docs/development.md
Fixed wording/typo in the development docs. Feel free to change it as you see fit. 
-----
[View rendered docs/development.md](https://github.com/davidklebanoff/probot/blob/patch-1/docs/development.md)
> Fixed Wording/Typo In The Development Docs

- src/manifest-creation.ts
- test/manifest-creation.test.ts
Looks like I missed this one. Requires #886
Finishes the final task, and closes #582
> test: Convert manifest creation test to TS

- package-lock.json
- package.json
> Greenkeeper/@octokit/graphql 2.1.1

- .github/issue_label_bot.yaml
label aliases so they can align with your pre-existing labels! 🚀 
Thanks for installing ❤️ our app.
> chore: Create issue_label_bot.yaml

- package-lock.json
- package.json
- src/apps/stats.ts
- test/integration/webhook.test.ts
> remove deprecation message

- package-lock.json
- package.json
Closes https://github.com/probot/probot/issues/942
> Bump octokit app dependency

- docs/development.md
Let me know if anything missing in the commit message or the PR title/desc, etc.
-----
[View rendered docs/development.md](https://github.com/grount/probot/blob/documentation/docs/development.md)
> docs: Improve development.md documentation

- package-lock.json
- package.json
closes https://github.com/probot/probot/pull/1004
> Update nock to the latest version 🚀

- package-lock.json
- package.json
- src/@types/@octokit/graphql/index.d.ts
- src/github/graphql.ts
- src/github/index.ts
- migrated to `graphql@v4`.
Fixes #999  and Closes #1000 
Closes #986 
Closes octokit/graphql.js#52
> fix: update `@octokit/graphql` to v4

- docs/extensions.md
- docs/pagination.md
- package-lock.json
- package.json
- src/context.ts
- test/context.test.ts
fixes #1021
-----
[View rendered docs/extensions.md](https://github.com/probot/probot/blob/prepare-for-update-to-latest-octokit/docs/extensions.md)
[View rendered docs/pagination.md](https://github.com/probot/probot/blob/prepare-for-update-to-latest-octokit/docs/pagination.md)
> Update to @octokit/rest v16.29.0

- package-lock.json
- package.json
This is just the result of running `npm audit fix`.
> fix: update insecure dependencies

- package-lock.json
- package.json
- test/webhook-proxy.test.ts
Updates return type for changes made in @types/express-serve-static-core by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39025
Fixes #1059 and fixes #1058
> fix: Use return value of `this` instead of a class

- package-lock.json
- package.json
- src/@types/@octokit/plugin-enterprise-compatibility/index.d.ts
- src/github/index.ts
fixes #1063. Sorry, v1.2.0 was supposed to be v2.0.0 😅
> @octokit/plugin-enterprise-compatibility v1.2.0

- bin/probot.js
> feat(cli): warn the user on passing in unknown commands

- bin/probot.js
closes #1098 
It is weird that `commander.js` API is not behaving as intended. This is a manual workaround in that regard.
> fix(cli): fixup invalid args validation

- bin/probot.js
- package.json
Minor stylistic code refactoring as a first step to address #1102
> chore: minor code refactoring

- script/publish-docs
Removes tagging added from 36332f8c7b5febe707eb44ecc9c2c3cc8ae698c5.
Merging this PR closes #1104
> chore: remove tag creation all-together

- bin/probot.js
- package-lock.json
- package.json
closes #1102
Follow up of #1103
> feat(cli): notify users of an available update in a non-intrusive way

- package-lock.json
- package.json
- src/@types/@octokit/plugin-retry/index.d.ts
- src/github/index.ts
> Update `@octokit/plugin-retry` to v3.0.1

- .github/workflows/docs.yml
Fixes issues relating to [build failures](https://github.com/probot/probot/runs/417944714).
> ci(docs): run script via default shell

- package-lock.json
- package.json
- src/application.ts
- src/apps/stats.ts
- src/context.ts
- src/github/index.ts
- src/github/pagination.ts
- src/index.ts
- test/fixtures/octokit/mock-response.ts
- test/index.test.ts
fixes https://github.com/probot/probot/issues/1131
> Update to @octokit/rest 16.43.1

- docs/deployment.md
Fixes #985
-----
[View rendered docs/deployment.md](https://github.com/styfle/probot/blob/patch-1/docs/deployment.md)
> docs: update ZEIT Now deployment instructions

- docs/best-practices.md
- src/context.ts
Fix #1187 by documenting configuration and security considerations.
-----
[View rendered docs/best-practices.md](https://github.com/hiddewie/probot/blob/patch-1/docs/best-practices.md)
> docs: Add documentation for including branch/fork context into configuration

- src/context.ts
@viceice proposed this change in #1209, but I found no pr was mentioning this issue.
> fix: Changes type of context.config()

- package-lock.json
- src/application.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
- test/index.test.ts
> fix: read GHE_HOST configuration and set `baseUrl` for Octokit instances at a single place

- docs/testing.md
- src/github/octokit.ts
- src/index.ts
- test/application.test.ts
Do `ProbotOctokit.defaults({ retry: { enabled: false }, throttle: { enabled: false } })` instead, which is much more explicit
-----
[View rendered docs/testing.md](https://github.com/probot/probot/blob/remove-ProbotOctokitCore/docs/testing.md)
> fix: remove `ProbotOctokitCore`

- package-lock.json
- package.json
This will set the `Users` column in Sentry's Issues table. That way you know how many of your GitHub App's installations are affected by the tracked error
> feat(sentry): set user ID to `installation.id` and username to repository owner login (when present)

- src/apps/setup.ts
- src/index.ts
- test/apps/setup.test.ts
> feat(setup): increase readability of welcome message

- .github/workflows/test.yml
> ci: add CODECOV_TOKEN env variable

- src/apps/setup.ts
- src/index.ts
- test/apps/setup.test.ts
This resolves the two recently added TODOs
> fix: use custom host in new welcome message

- src/context.ts
- src/index.ts
> feat: export WebhookPayloadWithRepository

- src/apps/setup.ts
Will close #1351
I still left the restart logic for glitch in there for now, If you want it gone I don't mind.
> feat: add restart message

- src/application.ts
- src/index.ts
- src/octokit/get-authenticated-octokit.ts
- src/octokit/get-octokit-throttle-options.ts
- src/octokit/get-probot-octokit-with-defaults.ts
- src/types.ts
- test/deprecations.test.ts
- test/index.test.ts
- test/integration/webhook.test.ts
> feat: deprecate `new Application({ throttleOptions })`

- src/context.ts
- src/octokit/get-webhooks.ts
- src/types.ts
- test/index.test.ts
I've fixed the errors. Let me know if this looks good.
cc: @gr2m
> fix(typescript): adapt for latest `@octokit/webhooks`

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/types.ts
- test-d/application.test-d.ts
- test/tsconfig.json
- test/types/application.test-d.ts
fixes #1388
You can see the failed check job before the fix here: https://github.com/probot/probot/pull/1389/checks?check_run_id=1302860150
> fix: correct payload type by omitting context keys

- package-lock.json
- package.json
> fix(deps): update `@octokit/core` to latest

- src/context.ts
- test/context.test.ts
- test/deprecations.test.ts
Long time coming ... sorry for all the deprecation message 😬. Part of #1309
> feat: `context.octokit`. Deprecates `context.github`

- src/create-node-middleware.ts
- test/create-node-middleware.test.ts
- test/deprecations.test.ts
addresses https://github.com/probot/probot/issues/1286\#issuecomment-740258978
> fix: load app function only once when using createNodeMiddleware

- docs/webhooks.md
- test/application.test.ts
- test/webhook-event-check.test.ts
-----
[View rendered docs/webhooks.md](https://github.com/probot/probot/blob/adapt-for-latest-octokit-webhooks/docs/webhooks.md)
> docs: `webhooks.on("*")` is now `webhooks.onAny()`

- docs/testing.md
resolves #1273
-----
[View rendered docs/testing.md](https://github.com/probot/probot/blob/1273/document-log-stubbing/docs/testing.md)
> docs: log stubbing

- src/helpers/resolve-app-function.ts
- test/fixtures/plugin/stub-typescript-transpiled-plugin.ts
- test/resolver.test.ts
> fix: import app functions transpiled from TypeScript

- src/probot.ts
- src/types.ts
> fix(typescript): remove `options.webhookProxy` from `Probot` constructor

- docs/deployment.md
- Added new example of a bot deploy on AWS Lambda using probot
-----
[View rendered docs/deployment.md](https://github.com/riyadhalnur/probot/blob/patch-1/docs/deployment.md)
> docs: new example for AWS Lambda

- docs/deployment.md
-----
[View rendered docs/deployment.md](https://github.com/ravgeetdhillon/probot/blob/netlify-functions-docs/docs/deployment.md)
> Netlify functions docs

- package-lock.json
- package.json
- src/octokit/octokit-plugin-probot-request-logging.ts
- src/octokit/probot-octokit.ts
> fix: bump `@octokit/plugin-rest-endpoint-methods` to v5

- package-lock.json
- src/run.ts
- test/apps/setup.test.ts
- test/create-node-middleware.test.ts
- test/create-probot.test.ts
- test/probot.test.ts
- test/run.test.ts
> fix: add workaround for "appId option is required" when in setup mode

- CODE_OF_CONDUCT.md
This updates to the latest version of the Code of Conduct template you are using.
-----
[View rendered CODE_OF_CONDUCT.md](https://github.com/AaronDewes/probot/blob/patch-3/CODE_OF_CONDUCT.md)
> fix: Update to Contributor Covenant v2

- src/apps/stats.ts
> fix: Do not crash when suspended in v9

- docs/development.md
Fix typo
-----
[View rendered docs/development.md](https://github.com/salihozdemir/probot/blob/doc-fixes/docs/development.md)
> docs: Minor fixes

- src/index.ts
Related to: https://github.com/probot/adapter-github-actions/pull/35
> fix(types): export `ApplicationFunction`

- package-lock.json
- package.json
Bump `@octokit/types` to `v7.1.1`
Fixes #1723
> build(deps): upgrade octokit/types to v7.1.1

- docs/testing.md
Added an example reference for a [bot tested with Mocha and Sinon](https://github.com/TomerFi/auto-me-bot/tree/main/tests).
-----
[View rendered docs/testing.md](https://github.com/TomerFi/probot/blob/add-mocha-test-ref/docs/testing.md)
> docs: added an example reference for a bot tested with mocha and sinon

- package-lock.json
- package.json
Upgrade `@octokit/types` to `v8`. This will make Probot's Octokit instance use latest types.
> build(deps): upgrade @octokit/types to v8

- docs/hello-world.md
update internal link (remove .md extension)
> docs: fix link

- src/types.ts
> fix(typescript): simplify ProbotWebhooks object

- docs/extensions.md
This fixes the curent existing liting issue in the beta branch
@wolfy1339
> Fix-linting of beta branch

- test/probot-octokit.test.ts
Solves the issues in v13 beta branch
> chore: solve codeql warnings

- .github/workflows/test.yml
> chore(ci): add node21 to ci/cd workflow

- docs/README.md
- docs/best-practices.md
- docs/configuration.md
- docs/deployment.md
- docs/development.md
- docs/extensions.md
- docs/github-api.md
- docs/hello-world.md
- docs/http.md
- docs/logging.md
- docs/pagination.md
- docs/persistence.md
- docs/simulating-webhooks.md
- docs/testing.md
- docs/webhooks.md
Related to https://github.com/probot/probot.github.io/pull/525, fixes the previous and next buttons on the docs which were not working properly anymore.
> docs: Fix previous/next button

- src/manifest-creation.ts
- test/integration/integration-smee.test.ts
Ensure, that the smee client works properly.
> test: add smee client integration tests

- test/views/__snapshots__/import.test.ts.snap
- test/views/__snapshots__/probot.test.ts.snap
- test/views/__snapshots__/setup.test.ts.snap
- test/views/__snapshots__/success.test.ts.snap
- test/views/import.test.ts
- test/views/probot.test.ts
- test/views/setup.test.ts
- test/views/success.test.ts
improve the coverage of the views. ;)
> test: 100 coverage for views

- README.md
- src/views/import.ts
- src/views/probot.ts
- src/views/setup.ts
- src/views/success.ts
- test/apps/__snapshots__/default.test.ts.snap
- test/apps/__snapshots__/setup.test.ts.snap
- test/views/__snapshots__/import.test.ts.snap
- test/views/__snapshots__/probot.test.ts.snap
- test/views/__snapshots__/setup.test.ts.snap
- test/views/__snapshots__/success.test.ts.snap
> chore: replace slack on heroku with gh-discussions

- docs/extensions.md
> fix: linting of beta

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Improve a little bit the workflows.
> ci: cosmetically improve, update and set permissions of/for workflows,

- package-lock.json
This removes duplicate versions of `@octokit/types` and `@octokit/openapi-types`
> build(lockfile): update `@octokit/oauth-methods` to 4.0.1

- src/context.ts
small self explainatory import fix.
> fix: avoid deep importing from dependency

- package-lock.json
- package.json
@wolfy1339 
Thank you for your code reviews :)
> fix: update @octokit/webhooks to v12.0.10

- package.json
- tsconfig.json
> chore: apply linting on tsconfig.json

- docs/deployment.md
prevent more issue like #1955 #1973
> docs: add necessary env suggestion for vercel

- src/octokit/get-webhooks.ts
- test/probot.test.ts
> fix(probot): passes logger to webhooks (#2010)

- docs/best-practices.md
Some typos have fixed in this PR.
> docs(deployment): fix typos in the markdown file

- package-lock.json
- package.json
- src/helpers/resolve-app-function.ts
- test/resolver.test.ts
I dont see any benefit in using the resolve dependency. We can make our implementation leaner :).
> fix: remove resolve dep

- package-lock.json
- package.json
Reverts probot/probot#2049 and fixes #2055.
> fix(deps): Revert "fix(deps): update dependency lru-cache to v11"

- src/context.ts
should fix #2103 
needs then to be applied in probot 14
> fix: memoryleak of octokit hook

- .github/workflows/test.yml
- README.md
> fix: remove codecov

- package-lock.json
- package.json
- src/bin/probot-receive.ts
- src/bin/probot-run.ts
- src/bin/probot.ts
- src/bin/read-cli-options.ts
- src/bin/read-env-options.ts
- src/bin/receive.ts
- src/create-probot.ts
- src/helpers/validate-event-name.ts
- src/helpers/validate-log-format.ts
- src/helpers/validate-log-level.ts
- src/types.ts
- test/helpers/validate-event-name.test.ts
- test/helpers/validate-log-format.test.ts
- test/helpers/validate-log-level.test.ts
This PR removes commander and use node native args parser
> probot14: Remove commander

- docs/webhooks.md
1. Enhanced explanations for webhook event handling.
2. Improved code examples for clarity and best practices.
3. Added structured sections for filtering actions and handling multiple events.
4. Ensured consistency and readability throughout the documentation.
> Improve Webhook Handling Documentation in Probot

- package-lock.json
- package.json
- src/apps/setup.ts
- src/helpers/webhook-proxy.ts
- src/server/get-printable-host.ts
- src/server/server.ts
- test/__snapshots__/server.test.ts.snap
- test/apps/default.test.ts
- test/apps/setup.test.ts
- test/create-node-middleware.test.ts
- test/e2e/e2e.test.ts
- test/run.test.ts
- test/server.test.ts
- test/server/logging-middleware.test.ts
- test/webhook-proxy.test.ts
before removing express, we should remove supertest
> deps: remove supertest

- src/helpers/webhook-proxy.ts
- test/webhook-proxy.test.ts
just a small cosmetic change to investigate why the other PRs maybe fail
> improve createWebhookProxy

- package-lock.json
- package.json
> Remove rimraf

- package-lock.json
- package.json
- test/e2e/e2e.test.ts
Rewrote the test, so that it uses native server and when i was at that I also upgraded execa in the beta branch. Now the e2e test should take about 1-2 secs instead of about 12 secs.
> test: improve e2e test speed, upgrade execa

- test/probot.test.ts
we should reduce the use of snapshots as they bring issues, when we want to to maybe change the engine one day
> test: use less snapshots, pt. 1

- .github/workflows/test.yml
The CI is setting REDIS_HOST but we need to set REDIS_URL, D'oh
> ci: fix redis tests

- package-lock.json
- package.json
- src/apps/setup.ts
- src/create-probot.ts
- src/helpers/update-env.ts
- src/manifest-creation.ts
- src/run.ts
- src/types.ts
- test/apps/__snapshots__/setup.test.ts.snap
- test/apps/setup.test.ts
- test/helpers/update-env.test.ts
- test/integration/integration-smee-create-channel.test.ts
- test/integration/integration-smee.test.ts
- test/manifest-creation.test.ts
- test/run.test.ts
- test/server.test.ts
- test/server/logging-middleware.test.ts
- test/webhook-proxy.test.ts
I wanted to improve the testability by removing mocks and do some "dependency injection" instead. 
And down the rabbit hole.
Only one test is failing in bun. Will have to investigate why the blocking of the port is not working as expected in the Github Runenr.
> refactor: improve setup testability, integrate update-env, improve test

- docs/development.md
- src/probot.ts
- src/types.ts
- test/probot.test.ts
mostly avoid using webhooks attribute,
need to rewrite some other parts to remove access to webhooks instance once and for all
> refactor: move variables of probot  into  state, use getters

- src/create-node-middleware.ts
- test/integration/integration-add-handler.test.ts
fixes the issue of @foxandi mentioned in https://github.com/probot/probot/pull/2152#issuecomment-2958960088
> fix: probot createNodeMiddleware respects expressjs next functionality
