probot/probot

lib/actions.js
lib/actions/assign.js
test/actions/assign.js

Given this config:
```yml
behaviors:
- on: issues.opened
then:
comment: "Hello New World!"
label: bug
assign: bkeepers
```
Here's what happened:

Add assign action

---

lib/actions.js
lib/actions/lock.js
lib/actions/unlock.js

Given these rules:
```yml
- on: issues.closed
then:
lock: true
- on: issues.reopened
then:
unlock: true
```
Here it is in action:
---
This PR brings up a couple issues/concerns:
0. Some actions are _really_ simple. I'm starting to wonder if there's a more declarative way to define actions that hit the GitHub API.
0. I'm not sure how to write tests for these kinds of actions. The existing action tests (e.g. [this](https://github.com/bkeepers/PRobot/blob/e257e5e259094c2c2c44b599d12a834162e368e9/test/actions/assign.js)) just mock out the GitHub API and check that the right params are passed to it. This feels pretty silly for actions that are just calling the API and nothing else.
0. There's a lot of duplication in extracting the issue params from the payload, which can probably be moved into …

Add lock and unlock actions

---

README.md
server.js

Even thought the use of GitHub Integrations (#36) is currently blocked, the Integration can still be used as an easy way to configure webhooks. The only caveat is that you have to give the @probot user access to the repositories.
I've stood up a [demo instance](https://github.com/integration/probot-demo) that can be used for people to test out the bot. This updates the README with directions for how to install it on a repository, and will automatically accept organization or repository invites.
cc #6

Easy installation

---

docs/configuration.md
lib/configuration.js
lib/context.js
lib/robot.js
lib/util/github-url.js
test/configuration.js
test/context.js
test/integration.js
test/util/github-url.js

This adds support for loading configs from other files.
```js
include(".github/triage.js");
```
```js
include("owner/repo:path/to/file.js#ref"); 
```
Closes #40

Load configuration from another file

---

lib/configuration.js
lib/workflow.js
test/integration.js

This adds a `contents` function for getting contents from the repository. Contents can be passed to any plugin method and will be automatically fetched.
```js
on('issues.opened').comment(contents(".github/NEW_ISSUE_TEMPLATE.md"));
// This also supports fetching contents from another repository
on('issues.opened').comment(contents("atom/configs:.github/NEW_ISSUE_TEMPLATE.md"));
```
Later optimizations:
- Right now the contents are fetched from GitHub whether they are used or not. It should only fetch the contents when they are needed.
Closes #42

Add method for getting repository contents

---

README.md

As https://github.com/bkeepers/PRobot/pull/36 got merged, no need to invite probot anymore

No need to invite probot as collaborator anymore

---

lib/configuration.js
lib/util/github-url.js
test/integration.js

This updates `include` and `contents` to default to the repository they were included from.
For example, given this `.probot.js`:
```js
include(`other/repo:script/js`)
```
And with `script.js` in `other/repo`:
```js
include('foo.js');           // Defaults to `other/repo:foo.js`
include('that/repo:foo.js'); // Override defaults
on('issues').comment(contents('file.md')); // Defaults to `other/repo:file.md`
on('issues').comment(contents('that/repo:file.md')); // override default
```
Fixes #75

Include content relative to source repository

---

lib/plugins/routing.js
lib/robot.js
lib/workflow.js

This plugin decouples robot.js from a repository, such that if an event payload doesn't contain a repository, it will default to a repo in the org called `probot-scripts`. From there, a config file can point to different repositories where further actions can be performed. 
Currently, there is a bug importing `configuration.js` into `routing.js`, which still needs to be resolved.

Add routing plugin

---

docs/configuration.md
lib/plugins/issues.js
test/plugins/issues.js

This adds a method for creating a new issue based upon a template specified in the config argument. The first line of the template creates the issue title, and the subsequent content makes up the body of the issue. 
Where the following line is added to probot.js:
> on('issues.closed')
.create(contents("IssueTemplate.md"));
And where `IssueTemplate.md` is:
>New Issue Title
>### Here is my test issue template
>
>- [ ] Issue Checklist
The resulting issue is created:
>![screen shot 2017-01-23 at 10 43 03 am](https://cloud.githubusercontent.com/assets/11798972/22215498/d0c7ec94-e158-11e6-827a-3b64501f98fa.png)

Add `Issue Creation`

---

docs/examples.md
lib/configuration.js
lib/context.js
lib/plugins/filter.js
lib/workflow.js
package.json
test/integration.js
test/plugins/filter.js
test/workflow.js

Fixes #81 
* Moves all conditional logic to `Filter` plugin
* Adds a _lot_ of specs
* Pass both `context` and `event` to filter functions to allow access to the GitHub API

Make filter into a plugin

---

script/bootstrap

`./script/bootstrap`  was failing on linux
```
./script/bootstrap: 8: ./script/bootstrap: [[: not found
```
Fixed by using POSIX compliant `[` instead of `[[`

Fix POSIX compliance on bootstrap

---

.env.example
docs/plugins.md
lib/robot.js

This makes it so you can call `robot.log("debug message")` in addition to `robot.log.debug("message")`.
```js
robot.log("This is a debug message");
robot.log.debug("…so is this");
robot.log.trace("Now we're talking");
robot.log.info("I thought you should know…");
robot.log.warn("Woah there");
robot.log.error("ETOOMANYLOGS");
robot.log.fatal("Goodbye, cruel world!");
```

Add shorthand for `robot.log`

---

lib/robot.js
package.json

This hacks the github client to use [bottleneck](https://github.com/SGrondin/bottleneck) to throttle requests to the GitHub API, allowing only 1 request at a time, and adding a 1s delay between requests as the [best practices](https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) guide suggests.
Fixes https://github.com/probot/stale/issues/10

Hack to throttle requests

---

docs/plugins.md
lib/paginate.js
lib/robot.js

Pagination of GitHub API results is something that every plugin author is going to need to deal with at some point. So this is a scenario that needs to be addressed in core.

Integrate pagination support into Probot core

---

lib/paginate.js

https://github.com/MarshallOfSound/probot-issue-duplicate-detection/pull/5 uses the `paginate` method to get a list of all issues in a repo. Since it just needs the concatenated list of all issues, it doesn't really need to pass a callback. So this PR updates `paginate` to have a default callback that just returns the response.

Update paginate to default to returning response

---

.gitignore
bin/probot-run
docs/development.md

Currently you are required to move the private key downloaded from GitHub to `private-key.pem`. This changes it to look for any `.pem` file.
cc #115

Look for any `.pem` file

---

.env.example
bin/probot-run
docs/development.md
docs/plugins.md
script/tunnel

This replaces ngrok with [localtunnel](https://github.com/localtunnel/localtunnel), which supports custom domains and has a node module, allowing it to be built right in to probot.
By default `probot run` will start a tunnel in development, using the `SUBDOMAIN` env variable or the local username.
```
$ npm start
Listening on https://bkeepers.localtunnel.me
```
cc @jbjonesjr

replace ngrok with localtunnel

---

docs/deployment.md

This adds centralized docs for deploying plugins so each plugin doesn't have to have its own docs.
Fixes #93 
Fixes #94

Docs for deploying plugins

---

package.json
test/context.js
test/robot.js

When writing Mocha tests, the blocks should be function expressions instead of lambdas.  The reasoning is that it's easier to refactor if a test needs a custom timeout, or needs to be conditionally skipped:
it('should do x', () => {
this.skip(); // throws exception
});
it('should do x', function () {
this.skip(); // ok
});

use function expressions in suite and test blocks

---

package.json

If a `probot` contributor has linked probot globally (via `npm link`), `npm start` will execute `probot` from the global npm prefix *instead* of the working copy.
The development workflow is a bit strange here, but if a contributor happened to `npm install localtunnel --save` in a working copy, `probot` won't recognize `localtunnel` *unless* the `start` script is specific about the path of the `probot` executable (it's a `NODE_PATH` issue).
May be an edge case, but using the relative path seems to fix it.

ensure "start" script runs from local directory

---

bin/probot-run
lib/plugin.js
package.json
test/fixtures/plugin/stub-plugin.js
test/plugins.js

- new behavior: if no plugins are specified, then they are automatically discovered.  if plugins are specified, no autodiscovery happens
- a plugin is defined as a module whose name begins with the prefix `probot-`
- move plugin loading/resolving routines into module
- add tests
* * *
Testing was a bit awkward here, as a user must save a plugin to `package.json` for it to be discovered.  This can be revisited in/after #101.

enable autodiscovery of plugins; closes #99

---

bin/probot-run
docs/deployment.md
lib/private-key.js
test/private-key.js

The loading preference is:
1. CLI flag
2. `PRIVATE_KEY`
3. `PRIVATE_KEY_PATH`
4. Find a `.pem` file in the current working dir
Changes:
- break out PK loading logic into module `lib/private-key.js`
- add more info to error messaging if probot fails to find a PK
- add tests
- add note to deployment docs

add PRIVATE_KEY_PATH env var support; closes #122

---

bin/probot-run.js

Commander only calls the function if an argument is provided. This updates the run command to find the private key if one is not provided with the command line options.
cc #127 @boneskull

Fix private key loading

---

docs/api.md
docs/plugins.md
lib/context.js
lib/robot.js
test/robot.js

`robot.auth()` is one of the first things called in almost every plugin to get an authenticated GitHub client. It's also been error prone because it's async and you have to prefix it with `await`, and omitting it gives a confusing error.
This PR sets `context.github` to an instance of the github client so it's just always available.
```js
module.exports = robot => {
robot.on('issues.opened', async (event, context) => {
const params = context.issue({body: 'Hello World!'});
return context.github.issues.createComment(params);
});
}
```

Include the authenticated client in context

---

docs/development.md

The "Install" button used to install an integration lives on the settings page of the integration, not on the settings page of the target repository.

Clarify development install flow

---

docs/plugins.md

These instructions referred to a file `autoresponder.js` which does not exist (a) for a plugin in general, or (b) for the autoresponder plugin in particular. The plugin template repo contains a file named `index.js` to export the plugin module, and this naming scheme seems to have been adopted widely (e.g. autoresponder, stale plugins both use `index.js`).

Update docs on running plugins locally

---

index.js
lib/robot.js
test/robot.js

Errors thrown in handlers from plugins were being silently ignored. This adds a catch around plugin handlers to log the errors, and updates how error logging is configured to ensure errors are always logged.

Catch and log errors from plugins

---

.env.example
README.md
app.json
bin/probot-run.js
docs/deployment.md
docs/development.md
docs/plugins.md
lib/private-key.js
lib/robot.js
test/private-key.js

GitHub Integrations were renamed to GitHub Apps. This is mostly a documentation update, but the one user-facing change is that the environment variable changes from `INTEGRATION_ID` to `APP_ID`, and the command line argument changes from `--integration` to `--app`.

Update name to "GitHub Apps"

---

index.js

Given:
```js
robot.log.info({repository}, `Cancel interval schedule`);
```
Before:
```
22:16:08.744Z  INFO stale: Cancel interval schedule (id=84828848, full_name=probot/stale, private=false, html_url=https://github.com/probot/stale, description="automatically close stale Issues and Pull Requests", fork=false, url=https://api.github.com/repos/probot/stale, forks_url=https://api.github.com/repos/probot/stale/forks, teams_url=https://api.github.com/repos/probot/stale/teams, hooks_url=https://api.github.com/repos/probot/stale/hooks, events_url=https://api.github.com/repos/probot/stale/events, tags_url=https://api.github.com/repos/probot/stale/tags, merges_url=https://api.github.com/repos/probot/stale/merges, created_at=2017-03-13T13:21:06Z, updated_at=2017-06-09T06:28:19Z, …
```

Add serializer for `repository` object

---

bin/probot-run.js
lib/server.js
lib/tunnel.js
package.json

When developing plugins, you have to restart the probot process to reload the code and localtunnel fails to reconnect about 50% of the time. I experimented with it and it just appears to be some race condition on the server. I didn't see anything [obvious looking through the code](https://github.com/localtunnel/server), but my guess is that it's not getting the disconnect from the first process until after the second connects, which then unroutes the newly connected client.
This PR updates probot to try making a request to the local tunnel and if it fails retrying to connect. Here's what it looks like.
```
$ npm start
Listening on https://bkeepers.localtunnel.me
^C
$ npm start
Failed to connect to localtunnel.me. Trying again (tries: 1)
Listening on https://bkeepers.localtunnel.me
```
cc …

Retry localtunnel

---

CHANGELOG.md
docs/plugins.md
lib/context.js
lib/robot.js
package-lock.json
test/context.js
test/robot.js

Callbacks passed to `robot.on` used to take two arguments—`event` and `context`. The second was pretty much just a fancy version of the first, and you really need the second to do anything useful, so the first argument has been dropped. (Technically, the second is passed as both arguments for now to preserve backward compatibility).
Before:
```js
robot.on('issues.opened', async (event, context) => {
log('Event and context? What is the difference?', events, context);
});
```
After:
```js
robot.on('issues.opened', async context => {
log('Sweet, just one arg', context, context.payload);
});
```
@lee-dohm @jbjonesjr @tcbyrd

Merge event and context arguments

---

docs/plugins.md

In #158 the event and context arguments to the callback got combined into one.
The documentation was still referring to the event object, which is no longer present.

Rename a reference to the combined context

---

CHANGELOG.md
lib/context.js
package-lock.json
package.json
test/context.js

#158 had a bug that prevented any events from being received. It was caused by the `events` getter, which was really just trying to support backward compatibility with projects using `context.event`. I don't see any public code that uses that, so removing the getter.
cc @hiimbex

Fix error when receiving events

---

bin/probot-run.js

The deprecation warning boiled down to: APP_ID is deprecated, set APP_ID instead.
The deprecated environment variable is named INTEGRATION_ID.

Fix typo in deprecation warning

---

CHANGELOG.md
bin/probot-run.js
index.js
lib/robot.js
package-lock.json
package.json
test/index.js
test/robot.js

This is a WIP to try to make it easier to test plugins. Here's basically how it works:
```js
const createProbot = require('probot');
const plugin = require('path/to/my/plugin');
const probot = createProbot();
probot.load(plugin);
probot.receive({
event: 'push',
// `push.json` has the payload copied from the webhook deliveries listed on GitHub
payload: require('./fixtures/push') 
});
```
@hiimbex @kytrinyx @lee-dohm #101

Make it easier to test plugins

---

docs/plugins.md

npm is never supposed to be capitalized (according to the npm folks themselves), so fix an instance where that wasn't the case.

Don't capitalize npm

---

docs/development.md

I know we mentioned finding a better way to restart the server in our last conversation, so I thought in the mean time it might be worth adding this npm module as an option that automatically restarts the server for you.
For me, a newbie to some development practices, it would've been nice to have this recommendation I think. Thoughts?
cc/ @bkeepers @kytrinyx

Add nodemon option to  development docs

---

bin/probot-run.js

Integration id was set to be removed in 0.7. We're past that version, so cleaning up the deprecated option.

Remove deprecated integration id

---

test/index.js

This test should fail while the current version is less than `0.10`. The previous logic was flipped (which was confusing to me) and failing because we are on exactly 0.9
This should allow the CI for #192 to pass.

Fix deprecation test

---

lib/context.js
test/context.js

Before:
```js
try {
const config = await context.config('foobar.yml');
// do stuff with the config
} catch (err) {
if(err.code !== 404) {
throw err;
} else {
// config was not found
} 
}
```
After:
```js
const config = await context.config('foobar.yml');
if (config) {
// do stuff with the config
} else {
// config was not found
}
```
cc @hiimbex

Return null if config is not found

---

index.js
lib/serializers.js
test/serializers.js

The serializer in #196 is causing the following log occasionally:
```
bunyan: ERROR: Exception thrown from the "event" Bunyan serializer. This should never happen. This is a bug in that serializer function.
TypeError: Cannot read property 'action' of undefined
```
This extracts the serializers so they can be tested, and fixes the event serializer to work if it's passed anything that doesn't look like a webhook event.

Add test for event serializer and fix cause of error

---

lib/context.js
test/context.js

This is an extension of #198 and [my original comment there](https://github.com/probot/probot/pull/198#issuecomment-321295433).
When calling:
```js
const content = await context.config('filename.yml', {foo: 'bar'});
```
If the config file is missing *and* a default config object has been passed, return that object instead of `null`.

Return defaultConfig

---

docs/plugins.md

I think it's worthwhile to draw more attention to these docs by giving them their own heading for now. Once we solidify the direction for docs and do that, this would probably be removed.
cc/ #205 @bkeepers

Add a temp docs link

---

package.json

XO was giving me a hard time so I fixed it 👍 
Prior to these commits, running `xo` via command line return **958 errors** (many of them tabs/spaces). Now there are 0 errors 🎉 All those errors were also showing up in my code editor.

Fix the linter

---

lib/robot.js
test/robot.js

In version `0.7.0` we deprecated event callbacks to instead of taking `(context, event)` to just a `context` that contains all necessary information. This was brought up re: https://github.com/probot/probot/pull/212#discussion_r134323462
This updates the` console.warn`, adds an inline comment, and adds a test to make sure this feature is deprecated by version `0.10`. 
I tried to research if there were any existing plugins that would be broken by this change and discovered these:
- https://github.com/tcbyrd/probot-lambda cc/ @tcbyrd
- https://github.com/akinori-i/PR-AnalyzeBot
- https://github.com/probot/no-response
I used [this search](https://github.com/search?l=JavaScript&p=1&q=event+context+probot&type=Code&utf8=%E2%9C%93), and I'm not sure if I caught all the cases. Any ideas on how …

Deprecate (context, event) for 0.10

---

bin/probot-run.js
index.js
package-lock.json
package.json
test/index.js

1. Pins the `github-webhook-handler` dependency to `v0.6.1`, which includes changes submitted by @bkeepers  in https://github.com/rvagg/github-webhook-handler/pull/24 to allow `GET` requests to get delegated to the next middleware instead of erroring out. 
2. Adds a command line parameter & config to support passing in a `webhookPath` variable. This allows the user to override the default `/` path used for webhooks. 
Fixes #202 - Serving static files should be completely doable from any route after these changes. 
/cc @tbarn @bkeepers @hiimbex 
--- 
I added tests but I also wanted to prove to myself that the command line options were working as expected. I ran probot using these options:
`./bin/probot-run.js --app 234 --private-key='index.js' -w '/webhook'`
*Note:* `--app` and …

Bumps webhook dep and adds webhookPath config

---

.github/config.yml

I _think_ the gif is supposed to be on a new line b/c it is in the [`config.yml`](https://github.com/probot/probot/pull/215/files#diff-51ae5ef21b0bd169a283475e122567d3L2) file. The `<br>` enforces this. 
I know this is not a pressing issue 🙃

Adds a line break

---

README.md

Eventually this will go on the website (https://github.com/probot/probot.github.io/issues/39), but documenting in the README for now.

Add link to slack channel

---

README.md
bin/probot-run.js
bin/probot-simulate.js
docs/README.md
docs/best-practices.md
docs/deployment.md
docs/development.md
docs/github-api.md
docs/hello-world.md
docs/http.md
docs/simulating-webhooks.md
docs/testing.md
lib/context.js
lib/plugin.js
lib/robot.js
test/fixtures/example.js
test/robot.js

As discussed in https://github.com/probot/probot/issues/207#issuecomment-323522926, this changes the terminology:
- **plugins => apps** - Akin to "react apps" or "rails apps", Probot apps are just node apps that have a dependency on `probot` and use features of the framework. They can be run standalone or combined with other apps with the `probot run` command. 
- **helper => extension** - Probot extensions are reusable modules that extend Probot itself.
`probot-scheduler` is currently the only example, but there are a few others I can imagine, such as `probot-command` which would do slash command handling similar to what @jbjonesjr's [snooze](https://github.com/jbjonesjr/probot-snooze) app does.
TODO:

Rename plugin => app

---

lib/robot.js
test/robot.js

Previously you could only use `robot.on()` in the following way:
```js
robot.on('issues.opened', async context => {
robot.log(context);
});
```
Now you can also pass an array to the first argument of `robot.on()` to do the following:
```js
robot.on(['issues.opened', 'issues.closed'], async context => {
robot.log(context);
});
```
This will allow for for example the following lines from probot/stale to be expressed slightly more neatly:
https://github.com/probot/stale/blob/257c8af485c8577d83d8c29fa9d0620fe373388e/index.js#L8-L13
Todo:

Multiple events per robot.on()

---

.github/stale.yml

II just realized when looking at open issues that we aren't eating our own dogfood (or drinking our own champagne). This adds the config for the stale app.

Create configuration for stale app

---

index.js
test/index.js
test/mocha.opts
test/server.js
test/setup.js

Fixes #224 by
- adding default [error handlers](http://expressjs.com/en/guide/error-handling.html) for express instances
- setting `LOG_LEVEL=trace` for all tests
- Move initialization of `logger` and other unchanged constants outside of the exported function in `index.js` to fix the warning about a potential memory leak due to `process.on(unhandledRejection, ...)` being called multiple times.
There's still one random thing being logged, but it should be removed in the next release:
```
DEPRECATED: the `SENTRY_URL` key is now called `SENTRY_DSN`. Use of `SENTRY_URL` is deprecated and will be removed in 0.11.0
```

Sssssssshhhh

---

README.md
docs/README.md

I noticed while linking someone to the repo that the README links to the docs in the repo, which are a little harder to browse. This updates it to use the intro copy from the docs, and then link to the docs on the website for more info

Link README to website

---

docs/extensions.md
docs/pagination.md

There are now two ([1](http://github.com/probot/scheduler), [2](https://github.com/probot/commands), and soon to be [3](https://github.com/probot/metadata)) extensions with released modules.
This adds a doc pointing to the existing extensions.

Document extensions

---

docs/github-api.md
docs/hello-world.md
docs/http.md
docs/pagination.md
docs/testing.md
docs/webhooks.md
package-lock.json
package.json

Thanks to @hiimbex's comment in https://github.com/probot/probot/pull/251#discussion_r138317160 about the docs not following the standard linting, this adds the eslint-plugin-markdown which enables linting of JS blocks in markdown docs.
Closes #239

Add eslint-plugin-markdown to lint docs

---

bin/probot-run.js

Setting `DISABLE_TUNNEL` to any value will prevent localtunnel from being set up, even if the development dependency is installed.
Fixes #259 
cc @wilhelmklopp

Add DISABLE_TUNNEL variable

---

lib/context.js

Fixes #256 - add a JSDoc `@example` for using the `context.config()` method with a `defaultConfig` object. I did build the docs locally, LGTM but feel free to check it out yourself.
🐟

Add @example for defaultConfig

---

.github/config.yml

Change the configured `newPRWelcomeComment` to use a smaller image that is less sp00ky and distracting.

Smaller image in the welcome PR comment

---

lib/robot.js

Currently, the note is shown as part of the example.
Is there anything else I have to do to update the docs?

Move the note for robot.log before the @example

---

lib/paginate.js
lib/tunnel.js
test/plugins.js

Noticed these still lurking unnecessarily since our switch to standard.

removes unnecessary eslint disables

---

README.md

Add a link to the new [ideas repo](https://github.com/probot/ideas) in the probot README.

Add link to ideas repo to README

---

README.md

Hello, and thanks for making probot -- it seems like a great tool.
I was working on a project that uses probot earlier today, and I had some difficulty finding the API reference, despite the fact that the documentation site is linked in the readme and a few other places. My process for trying to find the documentation was something like this:
1. I quickly skimmed the readme to see if the API was described in the readme itself.
1. I used command-F to look for the word "docs" on the https://github.com/probot/probot page, to see if it was mentioned in the readme. I didn't find anything related in the readme, but I did find a [`docs/`](https://github.com/probot/probot/tree/81ad1f2a46f9031030fc50bec74583bed05b2fcd/docs) folder in the repo.
1. I opened the `docs/` folder on GitHub, but I didn't …

docs: improve visibility of documentation site

---

lib/tunnel.js

Since localtunnel only takes lowercase values, and windows usernames can be in uppercase

fix: use lowercase username for localtunnel

---

lib/context.js

On Windows when I use `const config = await context.config('triage.yml');` I get the following error:
```sh
REQUEST:  { host: 'api.github.com',
port: 443,
path: '/repos/ocombe/test/contents/.github%5Ctriage.yml',
method: 'get',
headers:
{ host: 'api.github.com',
'content-length': '0',
Authorization: 'token v1.f013d09f149ef1fef8eb12e3172ff7e929dffabd',
'user-agent': 'NodeJS HTTP Client',
accept: 'application/vnd.github.v3+json' },
ca: undefined,
family: undefined }
STATUS: 404
HEADERS: {"server":"GitHub.com","date":"Tue, 31 Oct 2017 20:00:33 GMT","content-type":"application/json; charset=utf-8","content-length":"106","connection":"close","status":"404 Not Found","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4998","x-ratelimit-reset":"1509482850","x-github-media-type":"github.v3; …
```

fix: use posix join for config path

---

docs/README.md

This replaces the list of example apps with an include added in https://github.com/probot/probot.github.io/pull/101.

docs: Replace examples with include from website

---

bin/probot-simulate.js
index.js

When running tests that `require('probot')` with `jest --watch`, you'll eventually get:
```
(node:42819) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```
To reproduce it, save the following in a file and run it with `jest --watch`. Hit enter 10 times to re-run the test, and you should see the warning above appear.
```js
// example.test.js
const createProbot = require('probot')
test('MaxListenersExceededWarning', () => {
createProbot({})
})
```
This has to do with the way jest reloads code. This PR moves the registering of the `unhandledRejection` rejection listener to the `setup` method, which is called by the CLI scripts.

Move unhandled rejection listener to cli scripts

---

.travis.yml

I'd like to propose that we disable semantic-release when a PR is merged, and experiment for a while with continuing to use it manually.
We've been using semantic release for about 6 weeks now, and I feel like it has had a detrimental effect on the pace of the project. I know I've found the barrage of GreenKeeper updates on other repositories every time we merge a PR to be annoying, which causes me to hesitate before merging simple PRs. I've been noticing other people hesitant to make changes, or deciding against making changes, because it will bump the major version number.
Long term, I think I'd rather switch to something like https://github.com/johnbillion/probot-semver, where PRs are added to milestones for the appropriate next version and each release is thoughtful and intentional. …

Remove semantic-release from CI

---

docs/hello-world.md
docs/pagination.md
index.js
lib/context.js
lib/logger.js
lib/robot.js
lib/serializers.js
test/fixtures/example.js
test/robot.test.js
test/serializers.test.js

cc https://github.com/probot/probot/issues/320
This PR adds `context.log`, which will include information about the context in each log message.
```js
module.exports = robot => {
robot.on('issue_comment.created', context => {
context.log('Comment created')
})
}
```
```
17:42:05.326Z DEBUG Probot: Comment created
event: {
"id": "4cfd3e80-c575-11e7-8e7b-a2d9629ce9eb",
"event": "issue_comment",
"action": "created",
"repository": "robotland/test",
"installation": 13055
}
```
or with `LOG_LEVEL=json`
```json
{"name":"Probot","hostname":"Brandons-MacBook-Pro-3.local","pid":96993,"event":{"id":"afdcb370-c57d-11e7-9b26-0f31120e45b8","event":"issue_comment","action":"created","repository":"robotland/test","installation":13055},"level":20,"msg":"Comment …
```

Add `context.log` to add event context to each log message

---

docs/best-practices.md
docs/hello-world.md

There are some darn 404s popping up on the website, which are also causing new PRs to that repo to fail CI.

Fix two 404s to the API docs

---

bin/probot-run.js
lib/tunnel.js

This updates the messages about localtunnel to use the built-in logger:
cc #320

Use logger for localtunnel messages

---

lib/middleware/logging.js

After using this for a day or so, I don't think there's a lot of value in having the request/response headers in `debug`. The request headers are already logged with `trace` above when the request starts, so this removes the request headers from and switches logging of response headers to `trace`.
cc #320

Log full requests as trace

---

lib/index.js
lib/plugins/sentry.js
test/index.test.js
test/plugins/sentry.test.js

While doing a sweep for #320 I decided to extract the current sentry support to a built-in plugin, which makes it easier to test, and isolates it from the core of Probot. Someday this will likely be extracted into an extension that is configured at deploy-time, but this is at least a step in that direction.

Extract Sentry logging to a built-in plugin

---

bin/probot-run.js
lib/index.js
lib/webhook-proxy.js
package.json
test/webhook-proxy.test.js

localtunnel has long been a point of friction for developing Probot apps (https://github.com/probot/friction/issues/5). It's been down even more in the last week, which prompted a lot of discussion in Slack about looking more earnestly for a replacement.
I hacked together a [proof-of-concept](http://github.com/bkeepers/webhook-proxy) for a server that proxies webhooks using [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). 
How it works:
1. Go to http://github-webhook-proxy.herokuapp.com/, which will redirect you to a URL for a new channel. Use that URL as your **Webhook URL**
1. Any clients connected to that channel will receive the webhook events. Using this branch, set `WEBHOOK_PROXY_URL` to that URL and run `probot …

webhook proxy experiment

---

docs/deployment.md

As discussed in https://github.com/probot/friction/issues/17, this pull request updates the documentation for deploying to Zeit Now to indicate that the current deployment steps will not work due to an issue with their deploy script. It also provides a couple of workarounds.
I'm hesitant about this. On one hand, I think that it's silly to have documentation that directly references an issue. On the other hand, this saves potential victims of the bug (like me) a headache of trying to figure out what's wrong with the deployment process.

Update documentation to reflect now.sh private key issue

---

docs/deployment.md

Following the note at https://github.com/probot/friction/issues/5#issuecomment-350199754, this pull request addresses the start up command for Zeit Now not setting `NODE_ENV`. Without setting `NODE_ENV`, localtunnel issues are more noticeable when it goes down during deployment. Since localtunnel isn't even needed, and it's disabled with a production environment, the startup command should reflect this and set it manually.

Add NODE_ENV to Zeit Now boot command

---

docs/deployment.md

My hope with this pull request is to provide a good solution to the discussion in #366. I think that in general, as long as `now` is a stable platform, people are content with keeping it. With this in mind, I've done a lot of digging today. This pull request summarizes the research I did working with ZEIT staff. It also adds helpful documentation on how to make living with `now` way better in the long run.
This is an [undisputed problem](https://github.com/zeit/now-cli/issues/749), but we have two good workarounds in the docs so far, and with the amount of commotion I've drawn towards that issue, I think it might get resolved sooner, rather than later.
Resolved in a prior pull request.
In #366, I mentioned that `now` apps sleep automatically. This is true, by default. As shown in this PR, …

Improve Now documentation with scaling and aliases

---

.gitignore
test/serializers.test.js

Adds some tests to the serializer methods for that sweet, sweet code coverage. Also for reliability and all that. Also adds `coverage/` to `.gitignore` so that no one commits that by mistake.

Serializer tests

---

docs/github-api.md

Link out to the official GHE API docs where it mentions that GitHub Apps are enabled via an early access preview. [See here](https://developer.github.com/enterprise/2.12/apps/) for that link.

Improve GHE Docs

---

docs/extensions.md

This adds docs for the [probot-config](https://github.com/getsentry/probot-config) from our fine friends at Sentry (@HazAT @jan-auer).

Document probot-config extension

---

lib/index.js
lib/webhook-proxy.js
package.json
test/webhook-proxy.test.js

cc https://github.com/probot/smee/pull/28
Since Smee will likely evolve as features are added, this switches to using the smee client class (which was extracted from this code) to proxy webhooks. The biggest difference is that SmeeClient will forward requests at the HTTP layer, so it posts the event to `localhost:3000` instead of manually calling `probot.receive`. This has the advantage of using the same code path in development and production.

Use smee-client instead of EventSource directly

---

codecov.yml

This PR modifies the `codecov.yml` file to have it act a little nicer towards PRs that reduce coverage by a very small amount. Now, unless a PR reduces coverage by more than **3%** it'll still be marked as successful (let me know if this number needs to be further adjusted). It also changes the PR comment the Codecov app posts to be a little less obtrusive and large.
**Note**: This is yet untested, but from [following the docs](https://docs.codecov.io/docs/pull-request-comments) and using the [Codecov YAML validator](https://docs.codecov.io/docs/codecov-yaml#section-validate-your-repository-yaml) I'm fairly certain it'll work. I'm going to make the same changes in some other repos and see what happens, but in the meantime y'all can look at this PR.

Customize Codecov ☂️

---

lib/plugins/stats.js
test/plugins/stats.test.js

As discussed in office hours yesterday, the stats plugin isn't very scalable after a certain point.
You can now set the environment variable `DISABLE_STATS`, and the stats plugin won't load
cc @JasonEtco @bkeepers

Add option to disable stats

---

docs/deployment.md
docs/persistence.md

Adds the require front matter to the new persistence docs. I've placed it after Deployment but before Best Practices. Let me know if you think it should go somewhere else!

Add "next" front matter to Persistence docs

---

docs/best-practices.md

Per discussion in Probot slack, the best practices docs can get confusing when referring to "will only do X if the .yml file exists". This type of yaml-based config may be common in Github-oriented tooling, but it could do with an explicit call-out for users who aren't used to adding a lot of bots and companion tooling to their repos.

More explicit notes on yml config for target repos

---

docs/simulating-webhooks.md
docs/testing.md

Here is a little explanation about the `payload` object passed to `robot.receive` to simulate a webhook, that would have avoided me some trouble while writing unit tests in #407 😄 
Maybe some other changes can be relevant to make the docs clearer

Payload object explanation in documentation

---

docs/best-practices.md

Follow-up to #415 (another instance where clarification of "repository" => "target repository" is useful)

Further explicit note on yml config for target repos

---

docs/development.md

This pull request adds a note about the `.env.example` file that can be used as a template when following [Configure a GitHub App](https://probot.github.io/docs/development/#configure-a-github-app) to set the `WEBHOOK_PROXY_URL`.
Original issue: https://github.com/probot/friction/issues/20

Add `.env.example` template info

---

lib/github.js
test/github.test.js

Errors and 4xx responses from GitHub are currently being obscured since #400 by this error:
```
TypeError: Cannot read property 'meta' of undefined
42 |   octokit.hook.after('request', (result, options) => {
43 |     const {method, url, headers, ...params} = options
> 44 |     const msg = `GitHub request: ${method} ${url} - ${result.meta.status}`
45 |     logger.debug({params}, msg)
46 |   })
47 |   octokit.paginate = paginate.bind(null, octokit)
at EnhancedGitHubClient.octokit.hook.after (lib/github.js:44:62)
at invokeAfterHook (node_modules/before-after-hook/lib/register.js:96:12)
at Array.map (<anonymous>)
at node_modules/before-after-hook/lib/register.js:60:35
```
c69f2df updates the `error` hook to re-throw errors after logging them.
There's also a small tweak here to allow a …

GitHub fixes

---

package.json

https://github.com/davidbanham/express-async-errors/pull/4 is the cause
for https://github.com/gr2m/wip-bot/issues/42
Locking to 2.1.1 and will push out 5.0.1 release while we investigate of it's something probot is doing wrong, or if the PR to express-async-errors needs to be fixed.

Lock to express-async-errors 2.1.1

---

package.json

This copies the #432, which was a hotfix for v5, over to master. We need to find a better solution to https://github.com/probot/probot/issues/433 long-term, but this will do for now.

Lock to express-async-errors on master

---

README.md
docs/summer-of-code.md

Adds a section for Summer of Code, linking to [our doc on our website](https://probot.github.io/docs/summer-of-code). I also fixed a weird bug where my cell on the website was squished - not sure how that got in there 🤷‍♂️ 
Closes #446

Add Summer of Code section to the README

---

.github/config.yml

This tweaks the configs for welcoming new users:
- No longer point people towards probot/friction. I've seen multiple people open an issue here and then close it because the comment told them to. I think probot/friction is established enough now that we can just manually open issues over there as needed.
- Point people toward https://probot.github.io/community/ to get more involved
- Remove cat gifs, which will very funny, are a _little_ intense, especially when you open your first PR and get it merged.
- Use a slightly less intense (and more robot themed) gif to celebrated merged PRs

Update config for welcome app

---

docs/deployment.md

The [table of contents on the deployments page](https://probot.github.io/docs/deployment/) is missing [error tracking](https://probot.github.io/docs/deployment/#error-tracking).

Docs: Add error tracking to contents

---

docs/development.md

Updated Node.js Minimum version required from 7.6 to 8.3.0.
The is because Probot now uses object rest/spread properties, e.g., the rest spread operator: `{ foo, bar, ..., rest } = myObject`
This is available in version 8.3.0 (ES2018). See: [NodeJS ES2018 object rest/spread properties](http://node.green/#ES2018-features-object-rest-spread-properties)

Updated Node.js minimum  version required

---

docs/github-api.md
lib/github/graphql.js
lib/github/index.js
test/github/graphql.test.js

After playing around with #467 and looking at the source for `graphql-request`, I decided it'd be a lot easier and cleaner to just use `octokit.request` to make the GraphQL request. This branch adds `context.github.query` for making GraphQL requests.
I just ran this app to test it out, which uses GraphQL to fetch the body of an issue:
```js
module.exports = robot => {
robot.on('issue_comment.created', async context => {
const query = `
query repoId($owner: String!, $repo: String!, $number: Int!) {
repository(owner: $owner, name: $repo) {
issue(number: $number) { bodyHTML }
}
}
`
const data = await context.github.query(query, context.issue())
context.log(data.repository.issue.bodyHTML, 'Issue body')
})
}
```
FYI @koddsson

Add GraphQL support

---

lib/context.js

Replaced `myapp.yml` and `stale.yml` with `config.yml` as it is a recommended naming-convention applied in many Probot applications.

Replaced myapp.yml with config.yml

---

package.json

I forgot to remove this in #462.

chore: Remove github-webhook-handler

---

lib/github/index.js
lib/github/logging.js
test/github.test.js

Really minor tweak to allow this to work:
```js
const GitHub = require('probot/lib/github')
const github = new GitHub()
```

fix: allow initializing the GitHub client without options

---

lib/index.js

Resolves https://github.com/probot/probot/issues/466.
Moves `Webhook received` info events to the `debug` log level.
Perhaps there's a way I could make this optional or pare it down instead? 
I'm not sure what the best approach here for making it less obstrusive would be, please let me know!
/cc @zeke

Move webhookEvent info logs to debug level

---

CONTRIBUTING.md
README.md

This adds a badge for Twitter to the README, and moves the badges that are generally only relevant to contributors to `CONTRIBUTING.md`. The thinking here is that the README is more relevant to consumers of Probot who are building apps, and `CONTRIBUTING.md` is more relevant to people who are contributing to the project itself.
[![](https://img.shields.io/twitter/follow/ProbotTheRobot.svg?style=social&logo=twitter&label=Follow)](https://twitter.com/ProbotTheRobot)

Add twitter badge

---

package.json

The underlying issue here as fixed by switching from `github-webhook-handler` to `@octokit/webhooks` in #462.
Fixes https://github.com/probot/probot/issues/433

chore: relax version for express-async-errors

---

docs/deployment.md

Added additional details of deploying Probot App on Now.sh using now-cli.
Here, I have added `-e LOG_LEVEL=trace` to if the developer want s to get verbose logging, or can use `-e LOG_LEVEL=info` to show less details.

Added additional details about deploying on Now.sh

---

package.json

This enables 2 configs in ts-jest…
1. [enableTsDiagnostics](https://github.com/kulshekhar/ts-jest#ts-compiler--error-reporting)
> If you want to enable Syntactic & Semantic TypeScript error reporting you can enable this through `enableTsDiagnostics` flag
2. [skipBabel](https://github.com/kulshekhar/ts-jest#skipping-babel)
> If you don't use mocks, or synthetic default imports you can skip the babel-transpilation step.
The first one fixes the issue I was running into in https://github.com/probot/probot/pull/494#issuecomment-379957336 where the tests were passing with `npm test` but failing with `npm run build`. The second just removes a step we likely don't need.

Enable typescript diagnostics in ts-jest

---

docs/development.md

with the availability of `npm run lint` there is a need for some documentation. As other useful scripts like `test:watch` are being added, I think making a small subsection about them is good.

Added documentation for available npm run scripts

---

docs/extensions.md

In the current `docs/extensions.md`, on line 32, it's mentioned that config will be inherited from `probot-settings` repo, however in the following text describing it, the repo name given is `github-settings`. Of these only one can be correct. This PR intends to fix this discrepancy.

Modified conflicting statement in docs

---

docs/extensions.md

This extension has been around for a while but I just realized it's not currently on the list.

docs: Add probot-attachments to extensions list

---

lib/context.js
test/__snapshots__/context.test.js.snap
test/context.test.js

fixes #506 . Throws error for events which are not in `context.repo()`

Fixed error for installation event

---

docs/webhooks.md

Added details about how one can use wildcard event details. Added this because just like one recommends new developers building apps on Probot to subscribe to all the GitHub events for testing purpose, similarly, the GitHub wild card event will help developers to take actions for all the possible webhooks.

Added Wildcard Event detail

---

src/index.ts

Moving to TypeScript makes it pretty obvious that Probot needs some refactoring. This is the start of that.
First up: refactor the `createProbot` function into a class.

Refactor createProbot function into a class

---

package.json
src/github-app.ts
src/github/graphql.ts
src/github/index.ts
src/github/logging.ts
src/github/pagination.ts
src/github/rate-limiting.ts
src/index.ts
src/logger.ts
src/resolver.ts
src/robot.ts
src/serializers.ts
src/server.ts
src/webhook-proxy.ts
src/wrap-logger.ts
tslint.json

This PR is against #372
- `npm run lint` and run it as part of the tests instead of running `standard`
- Removes customizations to `tslint.json` and fix resulting linter warnings

Fix typescript linting

---

docs/deployment.md

Due to Zeit fixing the issue with the private key, this step is no longer needed.

Remove the now obsolete step

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md

Adds some issue templates, one for **Bug Reports** and one for **Feature Requests**. I've basically copy-pasted the templates [used by Babel](https://github.com/babel/babel/tree/master/.github/ISSUE_TEMPLATE); they fit well for us too, but feel free to suggest changes if you see something that needs tweaking.
cc @RichardLitt #522

Issue templates

---

lib/plugins/stats.js
test/plugins/stats.test.js

Prompted by https://github.com/probot/probot.github.io/pull/171 which has our site tests failing due to a spammy user being returned from the API.
cc/ https://github.com/probot/scheduler/pull/17 for prior art 
I think we shouldn't alter the total number of installations to remove spammy users and just not list them individually. I wasn't sure the best approach for this and obviously the test that already existed and the one I wrote are failing, so I could use some help!!

add ignore spammy/abusive user option for stats endpoint

---

.travis.yml

This PR adds Node.js `9.x.x` and `10.x.x` to the TravisCI builds.
I'm not saying that we should support every bleeding edge version of Node (that'd be great, I just don't think we have the bandwidth). However, we should be aware of what is and is not supported, and what will straight up not work.
TravisCI will run our existing tests in Node.js 9 and 10, always using the latest `minor/patch` version of those respective major versions.
---
_Note: Everything here passes 🎉 that means that we can now tell people that if they want to use Node 9/10, they **totally can**. That was the original goal of this PR._

Test Node 9 and 10 in CI

---

package.json

Closes #465. I’ll make sure we don’t break probot with 15.x.x versions despite probot using internal APIs

Update @octokit/rest to ^15.6.0

---

src/context.ts
src/github/graphql.ts
src/github/index.ts
src/github/logging.ts
src/github/pagination.ts
src/github/rate-limiting.ts
src/robot.ts
test/github.test.js
test/github/graphql.test.js

This makes a few naming tweaks to Probot's GitHub API.
- Renames `OctokitWithPagination` to `GitHubAPI` - This was bothering me because it adds more than just pagination to the octokit client. Ideally, we would just extend the `Octokit` definitions, but I couldn't figure out a good way to do that.
- Drops `EnhancedGitHubClient` function with `GitHubAPI` function - So now `GitHubAPI` is both the function exported from `./github`, and the Octokit+extensions interface.
I'm still getting comfortable with TypeScript, so I'd love a detailed review from folks that are more familiar.

TypeScript: tweaks to GitHub API

---

docs/github-api.md

🎉 Resources in webhooks and all API responses now include `node_id`: https://developer.github.com/changes/2018-05-30-end-jean-grey-preview/
Huge thanks to @bswinnerton and @d12 (and probably a few others) for their work. This will make it so much easier to use GraphQL + REST in the same app.
cc #476

docs: Simplify GraphQL example

---

docs/best-practices.md
docs/deployment.md
docs/extensions.md
docs/github-api.md
docs/hello-world.md
docs/http.md
docs/logging.md
docs/pagination.md
docs/persistence.md
docs/testing.md
docs/webhooks.md
src/application.ts
src/index.ts
src/logger.ts
src/plugins/default.ts
src/plugins/sentry.ts
src/plugins/stats.ts
src/wrap-logger.ts
test/application.test.js
test/fixtures/example.js
test/index.test.js
test/plugins/default.test.js
test/plugins/helper.js
test/plugins/sentry.test.js
test/plugins/stats.test.js

I don't like the word "bot" for most purposes (nevermind the name "Pro**bot**", we'll deal with that later).
A "bot" is software that mimics a human, but maybe more efficiently, cheaply, or dependably (pick two). We tend to personify bots, turning them into an "algorithm with eyes", as @galaxykate calls them.
Conversely, an "app" is software that is _used by_ a human. We aren't tempted to make it act like a human, but instead embrace the affordances of the environment that the app runs in.
So why don't I like the word "bot"? The reason is pretty simple: rather than encouraging people to write software that mimics a human, I think we should be encouraging people to write apps that do something a human _can't_ do. Some apps will act like bots, but it should be the exception rather than the …

Rename robot to app

---

src/github/index.ts
test/__snapshots__/context.test.js.snap
test/context.test.ts
tsconfig.json

This converts `test/context.test.js` to TypeScript. There's not really any other significant changes to get it passing besides adjusting where `OctokitError` extends `Error`.

TypeScript: convert Context tests

---

package.json
src/@types/promise-events/index.d.ts
src/application.ts
src/context.ts
src/github/graphql.ts
src/github/index.ts
src/github/pagination.ts
src/github/rate-limiting.ts
src/index.ts
src/middleware/log-request-errors.ts
src/middleware/logging.ts
src/plugins/stats.ts
src/private-key.ts
src/wrap-logger.ts
tsconfig.json

This isn't ready yet, but wanted to show what is done so far.  I turned on `noImplicitAny` in `tsconfig.json` and went through all of the files that needed types in parameters.  There were a couple I put `any` because I couldn't tell what they were exactly (such as https://github.com/szeck87/probot/blob/enable-noimplicitany/src/github/pagination.ts#L11).  Three files still need work.  I could use some guidance on:
* src/github/pagination.ts:  responsePromise.  It doesn't like a type of `AnyResponse` or `Promise<AnyResponse` in the callbacks, so not sure what to use there.
* src/middleware/log-request-errors.ts:  `req`, `res`, and `next`
* src/middleware/logging.ts:  `req`, `res`, and `next`, as well as the `logger` bind.

Remove noImplicitAny and add types to params

---

docs/configuration.md
docs/extensions.md

The more I thought about https://github.com/probot/probot/issues/534, the more I saw it as a great opportunity to add docs about all of our different configuration options.
I purposefully left out any variables specific to the [persistence database stuff](https://github.com/probot/probot/blob/master/docs/persistence.md) or the [deployment stuff](https://github.com/probot/probot/blob/master/docs/deployment.md) as well as the `SUBDOMAIN` (localtunnel relic) variable since we are deprecating it.
I'm not sure the best place for this on the website in the ordering of other docs, but preferably somewhere hidden, since many of these options are powerful as well as unnecessary. (I still need to place it somewhere in the doc ordering with a `next` block at the top).
Would love feedback/thoughts …

add env config docs

---

src/plugins/stats.ts

Previously, the stats endpoint would still fetch all repositories before checking if the account was ignored. This moves the check for ignored account before fetching all repositories to save a lot of time on spammy installations with a lot of repositories.

Optimize IGNORED_ACCOUNTS check

---

docs/testing.md
src/application.ts
src/index.ts
test/application.test.js
test/index.test.js
test/plugins/helper.js

This PR adds a new method to the `Application` class:
```js
app.load(require('./path/to/plugin')
```
Its a very small method, but just adds a little but of sugar around loading up an app. The paradigm of calling your app as a function isn't super approachable (JS-wise it makes sense, but people aren't used to exporting a function), but calling `.load()` on something is more commonly used.
<details>
<summary>I've solved this, but expand if you're curious!</summary>
@tcbyrd - my Typescript knowledge reached its limit within typing about four characters. I'm seeing this error:
```
ERROR: /Users/jasonetco/dev/probot/src/application.ts[41, 24]: Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like `() => void`.
```
Which I understand but don't …

app.load()

---

src/application.ts
test/__snapshots__/index.test.js.snap
test/index.test.js

This PR adds a check to see if the `GHE_HOST` environment variable includes a protocol following this RegEx:
```js
/^https?:\/\//
```
The following error is thrown:
> Your `GHE_HOST` environment variable should not include a protocol.
---
I just have one question about my implementation if anyone wants to chip in: I added this check in `app.auth()`, which means it'd throw when thats called, not when the app starts. Should I move the check elsewhere? I did it this way because `process.env.GHE_HOST` isn't referenced anywhere else.
Closes #569

Throw if GHE_HOST includes a protocol

---

src/github/graphql.ts
src/github/index.ts
test/github/graphql.test.js

The API path should be <ghe_host>/api/graphql, but it is defaulting to <ghe_host>/api/v3/graphql.

Fix path to GraphQL API when using GitHub Enterprise

---

docs/configuration.md

Reverts probot/probot#578
Sorry I missed the original ping for this PR, but the configuration.md file already has an option for `DISABLE_STATS`: https://github.com/probot/probot/blob/master/docs/configuration.md and [here](https://github.com/probot/probot/pull/591/files#diff-76e731333fb756df3bff5ddb3b731c46L25)
So this reverts that PR to keep the original. Happy to update the language on the original if that makes sense.

Revert "Configuration: DISABLE_STATS=true"

---

docs/best-practices.md
docs/hello-world.md

These are currently causing builds for the website to fail because these links changed from:
https://probot.github.io/api/latest/Context.html#config
and https://probot.github.io/api/latest/Application.html
to https://probot.github.io/api/latest/classes/context.html#config
and https://probot.github.io/api/latest/classes/application.html
which includes `classes` in the path. Not sure why this change is necessary, but assuming it's just a result of switching to ts doc generation, we can just update these links in our docs.

Update links for our API

---

src/context.ts

We seem to have unintentionally introduced a breaking change (which I'd call a bug) where `context.event` became the full event object `{ event: 'a-string', payload: {} }` instead of just the actual webhook event.
@tcbyrd and I nailed it down to this commit https://github.com/probot/probot/commit/e51dd016dc0ef8e96622dd54fcbbf4b56e61c75a in which `this.event = event` overrides the previous line's `Object.assign(this, event)` for just that `event` property.
The main reason this is a bug, aside from it being an unintentional breaking change, is that now we have `context.event.payload` and `context.payload`, which are exactly the same.

Remove extra event property on Context

---

package.json

@gr2m I noticed greenkeeper hasn't been opening PRs for new Octokit versions, so we got a bit behind. This gets us back up to v15.9.4 and 4.0.0 for webhooks. Now that 7.0 is out I'll be able to pay attention to this more, but we should probably figure out why Greenkeeper hasn't been notifying us.

Update ocotokit/rest.js to v15.9.4

---

src/application.ts

Set a default value of false and update the property to note that it
will now always be a boolean
---
As per https://github.com/probot/probot/issues/512#issuecomment-396595637
There are still issue with default values for app and cache, but they'll go away once #563 is merged

Make cacheErrors option optional

---

docs/configuration.md

The layout on https://probot.github.io/docs/configuration/ makes the descriptions hard to read. This attempts to clean it up a bit by:
1. move the required/optional indicator into the description to avoid taking a whole column.
2. Remove the example column and just include any applicable sample values in the description
3. Tweak language on several of the descriptions.
Before:
After:

Tweak formatting of config docs

---

package.json
test/context.test.ts
test/tsconfig.json

`tslint` isn't currently running against our test files. This is because the `--project` option looks at `tsconfig.json` to see which files the linter should run against, and that config only specifies `src`. If you add `test` to the list, then all the tests will be transpiled into `lib`, which is not exactly what we want.
I searched around a bit and couldn't really find any definitive answers for getting tslint to run against tests, but I did see a few mentions of creating another `tsconfig.json` for the tests that extends the existing config and adds `test` to the includes, so that's what I did here.
Edit: `tsc` wasn't being run against the tests either, which has now caught a bunch of other issues.

Run tslint against tests

---

docs/configuration.md
docs/development.md

See: https://github.com/probot/probot/issues/607#issuecomment-403164780 for background.
GitHub Apps make the Webhook secret optional; however, we (through octokit/webhooks) require it for probot apps.
Currently if you don't set a webhook secret, the error message for that is being silenced, so in the meantime and as a clarification we can update our docs briefly to explain that we have this as a requirement, even if GitHub doesn't.

Clarifies the Probot requires a webhook secret

---

docs/testing.md

Updating the testing docs so that they are the same as here: https://github.com/probot/template/pull/74
Is there another place where we should update this test example?
cc @JamesMGreene

Bring testing docs in line with probot/template

---

bin/probot-simulate.js
src/@types/@octokit/webhooks/index.d.ts
src/application.ts
src/context.ts
src/index.ts
src/serializers.ts
test/application.test.ts
test/context.test.ts
test/index.test.js
test/serializers.test.js

These changes were pulled out of #565 to try to slim that PR down.
Notable changes:
- Moves all type declarations for webhooks into `src/@types/@octokit/webhooks`. This is just a start and there's a lot of room for improvement for these types. Once we've had a chance to iterate on them a little, we can submit them upstream to `@octokit/webhooks`
- Deprecates `receive({event, ...})` in favor of using `receive({name, ...})`, which is what `@octokit/webhooks` uses. Apps using this method in tests should continue to pass, but they will see deprecation warnings. `context.event` is an alias for `context.name` and is not deprecated.
- Marks most `WebhookEvent` properties as optional. Until we get complete types for webhooks and some way to easily generate them, it's too much of a hassle to …

Extract type declarations for @octokit/webhooks

---

src/github/index.ts
test/github.test.ts
tslint.json

https://github.com/probot/probot/issues/582 Convert tests that `test/github.test.js`  to TypeScript. 
```
❯ npm run lint
> probot@7.0.1 lint /Users/Kentaro/workspace/github.com/probot/probot
> tslint --project test
ERROR: /Users/Kentaro/workspace/github.com/probot/probot/test/github.test.ts[2, 18]: Module 'nock' is not listed as dependency in package.json
```
Since `nock` was used only in tests, I added `no-implicit-dependencies` rule to tslint.json to avoid lint errors

Convert github tests to TypeScript

---

package.json

This fixes all tests not running in any environment.
Closes #639

Fixed jest tests not running due to insecure localhost warning

---

docs/development.md
src/application.ts
src/index.ts
src/plugins/stats.ts
src/resolver.ts
test/index.test.js
test/plugins/default.test.js
test/plugins/helper.js
test/plugins/sentry.test.js
test/plugins/stats.test.js
test/resolver.test.js

Stop using the names 'plugin' and 'app' to refer to instances of
ApplicationFunction.
This renames all variable names, but leaves the plugins folder in place,
to be renamed later
---
Partial fix for #632

Refer to instances of ApplicationFunction as appFn

---

bin/probot-run.js

I was looking at the code for `probot-run` and saw some old remnants of our `localtunnel` support. I think we've let the deprecation message run its course (especially since the comment here says to remove it in Probot 6, while we are now at 7).
Nod to #387 for original discussion on removing `localtunnel`.

Remove all remnants of localtunnel

---

docs/configuration.md
package.json
src/application.ts
test/application.test.ts

Add env var `INSTALLATION_TOKEN_TTL` to customise how long auth tokens are cached for internally.
- added to documentation
- calculated once on probot load
- only reduces cache time for auth tokens
Closes #637

Added env var INSTALLATION_TOKEN_TTL

---

src/resolver.ts
test/resolver.test.ts

Convert resolver tests to TypeScript

---

docs/http.md

`res.end()` is going to terminate the response process, and I believe this is not what the snippet is trying to acomplish.
Express API reference:
[res.send()](http://expressjs.com/pt-br/api.html#res.send) vs [res.end()](http://expressjs.com/pt-br/api.html#res.end)

Response object should call .send() and not .end()

---

src/private-key.ts
test/private-key.test.ts

Update private-key.ts to export the function without module.exports.
Change tests to typescript
Related to https://github.com/probot/probot/issues/582

Convert private-key tests to ts

---

package.json
test/application.test.ts
test/apps/stats.test.js

Closes https://github.com/probot/probot/issues/679
Updates octokit/rest which includes [this](https://github.com/octokit/rest.js/commit/830088c9ba41f2b5884157c240e47116cbefc522) endpoint update which is being [deprecated](https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/).

update octokit/rest and tests to use /app/installations

---

package.json

When cloning this repo, running `npm install`, and then running `npm test`, I see the following deprecation warning from Jest:
```
[ts-jest][DEPRECATED] - replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section of your Jest config with just "ts-jest".
```
This code change resolves this logged deprecation warning.

Resolve Jest transform option deprecation warning

---

test/apps/sentry.test.ts

See #582
This PR converts `tests/apps/sentry.test.js` to TypeScript.

chore(test): convert Sentry test to TypeScript

---

docs/deployment.md

Update deployment instructions for Now
Manually base64 encoding the the `PRIVATE_KEY` value and decoding it in a `now-start` hook is no longer necessary now that Probot [recognizes and decodes base64 encoded private keys](https://github.com/probot/probot/blob/f6946a0607fc835ef828bfb414aef8b234b02e56/src/private-key.ts#L30-L33). This should simply the deployment process as there is one less step for new users to get a Probot deployment up and running. 😊
-----
[View rendered docs/deployment.md](https://github.com/dmlittle/probot/blob/master/docs/deployment.md)

remove manual base64 encoding/decoding of private key

---

package.json
src/application.ts

This update was [failing](https://travis-ci.org/probot/probot/jobs/437917736#L475) due to octokit expecting a number for an installation id instead of a string.
This issue https://github.com/octokit/rest.js/issues/1001 led to octokit rewriting many `id` parameters for the API (correctly) as integers, where they were previously strings.
Not sure what npm version to consider this change since it has the potential to break people using API endpoints where they're passing strings as `id` values.

Update octokit rest

---

docs/deployment.md

[GitHub Actions](https://github.com/features/actions)—announced this morning—allows you to trigger workflows based on GitHub events, which makes it a great fit for running Probot Apps.
This PR adds documentation on running Probot Apps on GitHub Actions
-----
[View rendered docs/deployment.md](https://github.com/probot/probot/blob/add-github-actions/docs/deployment.md)

Document deployment to GitHub Actions

---

src/github/index.ts

Adds the `done` parameter to the `paginate` callback in the `GitHubAPI` interface. This partially fixes #670.

Add done parameter to paginate callback in GitHubAPI interface

---

docs/best-practices.md
docs/configuration.md
docs/hello-world.md
docs/http.md
docs/serverless-deployment.md
docs/simulating-webhooks.md
docs/webhooks.md

The inconsistency in our docs' names casing was bothering me, so this makes it more consistent.
-----
[View rendered docs/best-practices.md](https://github.com/probot/probot/blob/casing-matters/docs/best-practices.md)
[View rendered docs/configuration.md](https://github.com/probot/probot/blob/casing-matters/docs/configuration.md)
[View rendered docs/hello-world.md](https://github.com/probot/probot/blob/casing-matters/docs/hello-world.md)
[View rendered docs/http.md](https://github.com/probot/probot/blob/casing-matters/docs/http.md)
[View rendered docs/serverless-deployment.md](https://github.com/probot/probot/blob/casing-matters/docs/serverless-deployment.md)
[View rendered docs/simulating-webhooks.md](https://github.com/probot/probot/blob/casing-matters/docs/simulating-webhooks.md)
[View …

Follow GitHub Casing Standards

---

docs/development.md

`create-probot-app` was recently updated and removes support for the `typescript` flag. In this PR I documented how the `template` flag should be used. I'm unsure about the copy but for now this is what I came up with :). We should probably also explain users what the various templates include.
CC: @hiimbex 
-----
[View rendered docs/development.md](https://github.com/TimonVS/probot/blob/patch-1/docs/development.md)

Add documentation about template flag

---

src/manifest-creation.ts
test/manifest-creation.test.js

Including the version in the manifest, since GitHub supports that now.
This will enable us to make breaking changes to the manifest in the future which would be under a different version.
Tested that this works locally with `create-probot-app` but Glitch seems to now run out of memory when installing a dependency from a GitHub branch

Include version in manifest

---

package.json
src/apps/stats.ts
src/context.ts
test/context.test.ts
test/github.test.ts
test/index.test.js

~~This should pass once https://github.com/octokit/rest.js/pull/1094 is released.~~ **Update:** it does :)

update to @octokit/rest@15.18.0

---

src/apps/stats.ts

Before the typings file would be empty, now it will contain the proper typings

Fix typings for stats app

---

src/manifest-creation.ts

I have no clue how to test if this works or not, but I think this should do it. I did try _something_ tho: I did `npm i && npm start` which threw an error for me.
Any way for me to test if this addition works? 😅
Thanks! 💖
<hr />
Closes #712.

Prefill Glitch app name as GitHub app name for app manifests

---

docs/persistence.md

Fix broken link
-----
[View rendered docs/persistence.md](https://github.com/chadfawcett/probot/blob/patch-1/docs/persistence.md)

Fix link to "probot-metadata" extension

---

bin/probot-receive.js

Background
I have tried to use probot in GitHub Actions following [the instruction](https://probot.github.io/docs/deployment/#github-actions) and found that `probot recieve` has an issue: GitHub Actions sets the environment variable `GITHUB_EVENT_PATH=/github/workflow/event.json`, which is an absolute path, but `probot receive` prepends `process.cwd()` to the path and it fails to load the payload json file.
Proposal
I propose to use `path.resolve`, which resolves the path only when the given argument is relative (and in that case `path.resolve` prepends cwd when no other argument is given).

Use path.resolve instead of path.join to resolve payload paths.

---

docs/serverless-deployment.md

Related issue: https://github.com/probot/probot.github.io/issues/275
Sample codes for serverless deployment document are out of date and I fixed these codes according to the following page.
* https://github.com/probot/serverless-lambda#usage
* https://github.com/probot/serverless-gcf#usage
-----
[View rendered docs/serverless-deployment.md](https://github.com/kentaro-m/probot/blob/fix-doc-serverless-deployment/docs/serverless-deployment.md)

Fix sample code for serverless deployment

---

docs/serverless-deployment.md

The URL to the Serverless Configuration for GCF on [this](https://probot.github.io/docs/serverless-deployment/) page is broken. This PR fixes it.
-----
[View rendered docs/serverless-deployment.md](https://github.com/pgoodjohn/probot/blob/doc-fix-gcf-url/docs/serverless-deployment.md)

Fix URL for Serverless GCF repository

---

src/github/index.ts
src/github/pagination.ts

The callback in paginate method is always called with the response, not a promise:
https://github.com/probot/probot/blob/master/src/github/pagination.ts#L18
https://github.com/probot/probot/blob/master/src/github/pagination.ts#L24
Also the returned value should have type `any` instead of `void` cause the method expects that we return something.
Base also on your documentation:
https://probot.github.io/docs/pagination/

Fixed GitHubAPI.paginate callback signature

---

src/@types/@octokit/webhooks/index.d.ts

Before `event` is treated as `any`:
After:
The compiler was not reporting an error, but it was treating `event` always as `any`.
I've also added some definitions to get only `Error` as argument in case of listening to the `error` event. I've assumed that if you subscribe to `*` you can get an event or an error as argument in the callback. But not sure if that's true.

Fix webhook payload definition

---

src/apps/stats.ts
src/private-key.ts
test/private-key.test.ts

This is included in https://github.com/probot/probot/pull/751 and that change is approved by @tcbyrd via https://github.com/probot/probot/pull/751/files#r230205707
I want to make sure we get it in in case #751 is blocked
rebased on #818 to make tests pass

pass "utf8" as 2nd argument when reading private key from file using `fs.readFileSync`

---

docs/deployment.md

In the example `main.workflow`, `uses` inside an `action` must now take the form `owner/repo@ref`. This updates the GitHub Actions deployment documentation to reflect this.
/cc @JasonEtco 
-----
[View rendered docs/deployment.md](https://github.com/codebytere/probot/blob/update-actions-doc/docs/deployment.md)

doc: update GitHub actions workflow reference

---

src/@types/@octokit/app/index.d.ts
src/index.ts
test/__snapshots__/index.test.js.snap
test/index.test.js

To be able to use Probot `8.0.0-beta.*` with Github EE we need to provide our own `GHE_HOST` environment variable with the host. As Probot 8 `8.0.0-beta.*` now uses `@octokit/app` we have to pass `baseUrl` option there the same way we pass it to `@octokit/rest`.

fix: pass baseUrl option to @octokit/app

---

src/context.ts

The import of Webhooks from the `@octokit/webhooks` was incorrect, it is not a named export (see https://github.com/octokit/webhooks.js/blob/master/index.d.ts) but rather a default export

fix: octokit webhooks import

---

src/webhook-proxy.ts

In production where `smee-client` is a devDependency (something we recommend and is in the `create-probot-app` templates), `smee-client` doesn't exist so this functionality throws an error and prevents the app from starting up. This PR moves the `require` call back into the `try/catch` block to ignore `smee-client` if it isn't present.
cc @gr2m and #851

fix: Move smee-client require back to try/catch

---

package-lock.json
package.json

This PR updates two dependencies, `hbs` and `jest`, to fix some security vulnerabilities.
cc @wolfy1339 - thanks for suggesting this over in https://github.com/probot/probot/issues/859#issuecomment-468995233.
@gr2m - I'm assuming this'll cut a new release of `7.5.x` upon merging, since it'll be merged into the `7.x` branch? Let me know if that's not the case.

fix: Update dependencies

---

src/context.ts
src/github/index.ts
test/context.test.ts

This PR updates the `error.code` to be `error.status`, as recommended by a deprecation message in `@octokit/rest`. @gr2m I posed a question in #869 but I'll move it over here for posterity and ease-of-review:
> since we're using our own types for the OctokitError class - what's more correct here?
And you already answered:
> `error.status` is correct, it’s a number. It used to be the status text, that is a breaking change that comes with v8, so we should update it in probot
Closes #869

fix: error.code => error.status

---

package-lock.json
package.json

`npm audit` said there was something suspicious about `hbs` — it's gone now.

chore(dependencies): Update vulnerable packages

---

package.json

Currently, running `npm test` makes quite a few warnings pop up.
```
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.skipBabel" is deprecated, use "[jest-config].globals.ts-jest.babelConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
...
```
This PR makes them go away by replacing the deprecated `globals` setting with modern `preset`.
- See https://kulshekhar.github.io/ts-jest/user/config/#the-3-presets for more details.
- See https://jestjs.io/docs/en/configuration.html for default options for the rest.

test: Use modern Jest configuration format

---

src/application.ts

Allow to use this type directly when we want to create handlers with a function

feat: export type OnCallback

---

docs/development.md

use single quotes as double-quite causes error during "npm install"
-----
[View rendered docs/development.md](https://github.com/DenysVuika/probot/blob/patch-1/docs/development.md)

Fix description quotes

---

src/index.ts

Probot "eats" errors from application code. These are logged, but not propagated to `@octokit/webhooks` and not reported to Github. `@octokit/webhooks` responds with `200 OK` instead.
With this change the error is propagated to `@octokit/webhooks` and it correctly respond with error code `500`.

fix: propagate errors to @octokit/webhooks

---

docs/webhooks.md

This list of webhook names is a useful reference and appears to be kept up-to-date by robots and @gr2m: https://github.com/octokit/webhooks.js/blob/master/lib/webhook-names.json
Let's link to it from the Probot webhook docs!
-----
[View rendered docs/webhooks.md](https://github.com/probot/probot/blob/link-to-list-of-webhooks/docs/webhooks.md)

docs: link to events list in @octokit/webhooks.js

---

package-lock.json
package.json

see https://github.com/octokit/webhooks.js/issues/73

normalize payload string before verifying signature (via update to latest @octokit/webhooks)

---

src/index.ts

In `errMessage` the `err.message` may be undefined. We need to do a null check here.

fix: Check if err.message exists

---

package-lock.json
package.json

I've updated the js-yaml version to 3.13.1 to fix the code injection.
See https://www.npmjs.com/advisories/813

Fix js-yaml code injection

---

src/manifest-creation.ts
test/manifest-creation.test.ts

The [GitHub App manifest flow](https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/) is currently not working for _GitHub Enterprise Server_ instances.
When calling [`POST /app-manifests/:code/conversions`](https://developer.github.com/v3/apps/#create-a-github-app-from-a-manifest), we need to configure the `@octokit/rest` client to use the `GHE_HOST` environment variable.
/cc @wilhelmklopp who paired with me on researching this :bow:
____
(Note, I attempted to implement this when we [instantiate a new `GitHubAPI`](https://github.com/probot/probot/blob/23e8eabf4a29ace976f46ad64acd93da08a4af69/src/manifest-creation.ts#L60), but TypeScript was complaining, and I couldn't figure out why 😕)

fix: Support GitHub Enterprise Server in GitHub App Manifest flow implementation

---

src/wrap-logger.ts

Currently it is not possible to specify any fields for log lines using `child` other than the ones probot already specifies. Looking at the documentation of the underlying logging library used (https://github.com/trentm/node-bunyan#logchild) it shows any attribute can be used.

fix(typescript): log.child options

---

src/github/graphql.ts
src/github/index.ts
test/github/graphql.test.ts

This improves the readability of the deprecated method as IDEs will mark the method as deprecated if you use the correct tag:
This also helps for the tslint rule that checks for deprecated symbols.

docs: use typescript `@deprecated` tag

---

docs/testing.md

The previous testing example does not compile with newer versions of Probot (`"probot": "^9.2.15"`) because the type of `app.app` has changed.
```
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
status.test.ts:12:9 - error TS2739: Type '() => string' is missing the following properties from type 'App': getSignedJsonWebToken, getInstallationAccessToken
12         app.app = () => 'test'
```
-----
[View rendered docs/testing.md](https://github.com/cconstable/probot/blob/patch-1/docs/testing.md)

docs: Update creating Probot instance in testing docs

---

package-lock.json
package.json

The security software we are using flagged that there is vulnerable version of handlebars being pull in as a dependency of hbs 4.0.3. This is fixed in version 4.0.4, so the solution is simple enough!

fix: update hbs dependency to ^4.0.4

---

docs/best-practices.md
docs/extensions.md
docs/persistence.md
package.json
src/context.ts
test/context.test.ts

Implements the functionality of https://github.com/probot/probot-config in context.config. This adds the ability to have config fallback to a `.github` project in the target repository's organization, or for repository configs to specify a particular repository to merge config from.

feat: Implement probot-config on context.config (#619)

---

docs/configuration.md
src/logger.ts

Adds the ability to tell probot's logger to print log levels as strings.

feat: add LOG_LEVEL_IN_STRING to set bunyan-format levelInString option

---

src/index.ts

Probot is processing the `.env` file after the logger is [created (under the hood)](https://github.com/probot/probot/blob/fd6d6febf113d9be846785efceb2de812870b4fe/src/logger.ts#L61). This leads to bugs like #1032, where `LOG_LEVEL` is set in `.env` but its *level* is not being used.
By requiring `.env` config at the top, `logger.ts` will have the `LOG_LEVEL` environment variable.
**Fixes**
Fixes #1032

fix: Include dotenv config as early as possible

---

docs/deployment.md

Removes deployment section for GitHub Actions which should close #1028, @gr2m.
We should look at re-adding GitHub Actions deployment documentation once Probot v10 comes out.
If someone comes out with updated documentation before then, I'd be happy to use that too.
-----
[View rendered docs/deployment.md](https://github.com/MaximDevoir/probot/blob/fix/1028/docs/deployment.md)

Remove GitHub Actions deployment documentation

---

src/index.ts

Throw errors during startup if `NODE_ENV === 'production'` and the application is not in a usable state (defining "usable state" as conditions that prevent entering setup mode)
Fixes #1044

Throw at startup in prod if misconfigured

---

src/github/index.ts
src/github/pagination.ts

When using `github.paginate` in TypeScript, you cannot write a callback function that takes the `done` callback because this is missing in the `Paginate` interface. This PR adds the callback to that interface. Values for `callback` that only take one parameter still satisfy this type.

fix(typescript): add done callback to Paginate interface

---

src/github/index.ts
test/github.test.ts

The `onAbuseLimit` and `onRateLimit` provided by default with Probot return `undefined` and thus do not cause the throttling plugin to actually retry the request. This PR fixes those two callbacks, and also adds tests for both the throttle and retry behaviors.
I suppose this is technically a breaking change if someone is relying on the current behavior (e.g. not retrying by default)?

fix: Correctly retry requests after hitting rate or abuse limits

---

package-lock.json
package.json

Hi there! 👋 `cache-manager`, one of the dependencies used by Probot, recently accepted [a PR](https://github.com/BryanDonovan/node-cache-manager/pull/131) that unblocks [`@zeit/ncc`](https://github.com/zeit/ncc) from being able to [compile and run applications that need Probot](https://github.com/zeit/ncc/issues/480).
So I'd request a version bump of `cache-manager` from `^2.4.0` to `^2.10.1` to be able to use this.
Thanks for taking a look!

fix: bump cache-manager version to allow Probot compilation by @zeit/ncc

---

docs/testing.md

Nock should be setup properly so that net connect ONLY gets disabled before each test and then gets enabled and reset again AFTER each test. This is recommended by them here: https://github.com/nock/nock#resetting-netconnect
I bring this up because this really bit me as I used this example in the Probot docs for my Probot tests and when I was testing my express code in a complete separate test, when running `npm test` it would fail. But running the test by itself wouldn't.
This was because `nock.disableNetConnect()` was _bleeding_ onto other tests because it wasn't encapsulated properly.
-----
[View rendered docs/testing.md](https://github.com/moltenice/probot/blob/patch-1/docs/testing.md)

Nock not properly setup

---

package-lock.json
package.json
src/logger.ts

#1070  looks like a misconfigured type from `bunyan-format`.
`bunyan-format` returns the `stream.Writable` type:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/node/globals.d.ts#L640-L647
Meanwhile, `bunyan`'s `stream` option expects `NodeJS.WritableStream` from here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/node/stream.d.ts#L119-L125
We'll just assert the return type as `NodeJS.WriteableStream`.
Issue is being tracked DefinitelyTyped/DefinitelyTyped#40444.
Fixes #1070

fix: assert stream type

---

package-lock.json
package.json
src/logger.ts

Changes made in @types/bunyan-format 0.2.1 have been rolled-back and are now available in 0.2.2. A solution for @types/bunyan-format to interpret instances of callable/newable and return the correct type is being worked on.
Going forward with this package's updates, we shouldn't have to assert any types when calling with `new`.

chore: update bunyan-format and remove earlier type assertion patch

---

docs/persistence.md

This adds an example for connecting to a Postgres database using [`@databases/pg`](https://www.atdatabases.org/docs/pg.html), and updates the MySQL example to use [`@databases/mysql`](https://www.atdatabases.org/docs/mysql.html).
Because [`@databases`](https://www.atdatabases.org/) supports Promises out of the box, the examples become simpler, and because [`@databases` prevents SQL Injection vulnerabilities](https://www.atdatabases.org/blog/2019/07/29/sql-injection-in-node), it is much safer for users who may be new to node.js
-----
[View rendered docs/persistence.md](https://github.com/ForbesLindesay/probot/blob/patch-1/docs/persistence.md)

docs: add example using Postgres and update MySQL

---

.github/workflows/ci.yml

This PR adds a GitHub Actions workflow file to start using it for CI. This is mostly to standardize with other projects we're working on, and for all the benefits of Actions (logs in GitHub, speed of execution, no additional management controls).
I'd love to run this in addition to our Travis setup for a hot minute - we use Semantic Release through Travis, and I'd like to get this going for CI before tackling that.

chore(ci): Use GitHub Actions for CI

---

docs/development.md

This has been in my backlog since Create Probot App was converted to TypeScript.
* updated create-probot-app usage instructions
* removed deprecated `homepage` option
* updated create-probot-app output
* wording and punctuation adjustments
-----
[View rendered docs/development.md](https://github.com/MaximDevoir/probot/blob/chore/update-cpa-instructions/docs/development.md)

chore: update create-probot-app section

---

src/webhook-event-check.ts
test/__snapshots__/webhook-event-check.test.ts.snap
test/webhook-event-check.test.ts

Because `GET /app` does not include many events (e.g. `fork`, `installation`, etc.), we don't want to compare some events to the results of `GET /app`.
In these cases, webhook-event-check will silently ignore verifying whether the GitHub App is subscribed to the event.
Fixes #1091

fix: Limit webhook-event-check to known events in `/app` response

---

.travis.yml
script/publish-docs

Re-enable the `scripts/publish-docs` script by adding a stage to update the `docs/` submodule from [probot.github.io](https://github.com/probot/probot.github.io). 
See and fixes probot/probot.github.io#321.

fix: Add `publish-docs` stage to Travis build

---

script/publish-docs

This PR successfully updates [probot.io](https://github.com/MaximDevoir/probot.io) with [this build](https://travis-ci.org/MaximDevoir/probot/builds/631991282).
Take a look at my comment [below](https://github.com/probot/probot/pull/1101#issuecomment-570320071) to see what I believe was causing the previous docs-publish failure.

fix(ci): publish docs

---

package-lock.json
package.json

This PR updates hbs to 4.1.0, which uses safe handlebars version 4.5.3, and updates istanbul-reports to 2.2.7, which drops handlebars completely so that no [prototype access errors are written](https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access) to the console when running `npm test`.
As far as I know, this is only required to mute the `npm audit` errors; I'm not aware of ways to exploit handlebars vulnerabilities on probot.

Fix for multiple handlebars advisories

---

docs/configuration.md
src/application.ts
src/github/graphql.ts
src/index.ts
src/manifest-creation.ts
test/__snapshots__/index.test.ts.snap
test/github/graphql.test.ts
test/index.test.ts
test/manifest-creation.test.ts

This adds support for overriding the `GHE_PROTOCOL` to something like `http`. Although I don't expect this to be used outside of github (using a local github dev env), it can exist here with the warning in the config guide.
-----
[View rendered docs/configuration.md](https://github.com/jules2689/probot/blob/ghe-protocol/docs/configuration.md)

feat: Add support for GHE_PROTOCOL

---

docs/development.md

Based on my recent attempt at following these instructions, I've thought of a couple changes that may make things easier for fellow new users of this app. Great job, everyone. It is pretty awesome!
--
Having the private key download at the end leverages the image provided for 'APP_ID', in order to cue and instruct the user on how to get the `.PEM` file; and groups the steps to edit `.env` together, leaving the download for last. This enhances both the setup flow and its legibility.
Thought it would also be useful to add a link here to see the additional environmental configurations available.
-----
[View rendered docs/development.md](https://github.com/caravinci/probot/blob/patch-1/docs/development.md)

docs: change phrasing on how to get the private key

---

src/webhook-event-check.ts
test/webhook-event-check.test.ts

Yesterday, @travi brought to my attention that the `GET /app` route this feature calls had to be mocked under certain test conditions (see the linked [PR](https://github.com/probot/settings/commit/dcd7bd69b6534bba739807e2539126bc40d7e00d#diff-1d2e5ba7c00513700e614348ffe1bbb0)). I imagine that took some time to find because we haven't documented how or when the route needs to be mocked.
With this PR, we disable the feature in certain test environments to avoid requiring developers to add a stub mocking the `GET /app` route. This also allows developers to focus on mocking the requests that pertain to their application and *not* the requests from the developer enhancement tools provided by Probot.
Currently, this determines that Probot is in a test environment by looking to see if `NODE_ENV` …

fix: disable webhook-event-check in common test environments

---

script/publish-docs

Okay, so yesterdays *[fix](https://github.com/probot/probot/pull/1124)* wasn't [enough](https://github.com/probot/probot/runs/422571032).
This PR:
* Configures Git to be able to commit changes.
* Sets `REPO` alongside other top-level variables.
* Adds a description to the commit message about which change triggered the update.
This workflow has been [tested successfully](https://github.com/MaximDevoir/probot/runs/423699349) and you can see an example of the new commit message https://github.com/MaximDevoir/probot.io/commit/0c96e3a6a64c508ffe3d1fd700b49ff95e441306

ci(docs): fix Git setup on docs action

---

script/publish-docs

These PRs are endless... REPO declaration was removed in 0748bc6a83f81b95538d06fdd366e97723123f3b.

ci(docs): correctly set `REPO`

---

views/success.hbs

Recent change in the GitHub app installation workflow now 
requires that an app must be activated after installation. That
should be mentioned in the "success" page.

feat: mention that app must be activated after install

---

src/github/index.ts

Since we don't expose `ProbotOctokit`, we need to properly default to it if it's not passed in now that `GitHubAPI` is exposed. Sorry for missing this in my initial PR.

fix(github): provide default ProbotOctokit

---

src/github/index.ts

Forgot to update the type interface as well. I'm implementing my integration using this new API surface, so found this with VSCode type checking.

fix(github): Octokit is optional

---

docs/development.md

As of [this commit](https://github.com/probot/create-probot-app/commit/a6d4b9ad10aaacae168a0b0e7867445c2e5d516c), create-probot-app requires fs-extras v9, which in turn [requires Node 10](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md).
-----
[View rendered docs/development.md](https://github.com/ruricolist/probot/blob/patch-1/docs/development.md)

docs: Update minimum Node version

---

test/manifest-creation.test.ts
views/setup.hbs

Fixes #1115. Instead of complaining that it's been closed I figured I'd give it a shot at fixing it myself.
It was a bit of a pain to track down but in the end the fix is quite simple. The issue doesn't lie in the manifest being created incorrectly or the quotes aren't being escaped, it's actually in the template that's being rendered. See the below screenshot in the HTML, this value is being posted to Github and is obviously invalid JSON.
Changing the value to `{{ manifest }}` resolves the problem. While investigating this I also found some uncovered code in `getManifest`, so I added a unit test. I can move this to a separate PR if preferred though.

fix: quotation marks in setup description

---

.github/workflows/ci.yml

ci: run codecov only on `ubuntu-latest` and node 12.x

---

docs/deployment.md

- Zeit just rebranded to Vercel and this PR changes the deployment guidelines to deployment for gridsome
-----
[View rendered docs/deployment.md](https://github.com/Developerayo/probot/blob/probot-deployment-docs/docs/deployment.md)

[FIX] switch zeit now to Vercel Now for probot deployment

---

docs/webhooks.md

Current hyperlink takes you to a non-existent page. 
Before Change : https://github.com/octokit/webhooks.js/blob/master/lib/webhook-names.json
After Change : https://github.com/octokit/webhooks.js/
-----
[View rendered docs/webhooks.md](https://github.com/akmalick/probot/blob/patch-1/docs/webhooks.md)

docs: Correct URL

---

docs/configuration.md

Some default items in this file include a trailing period, some don't. It appears that the majority do not.
-----
[View rendered docs/configuration.md](https://github.com/jsoref/probot/blob/docs-configuration-punctuation/docs/configuration.md)

docs(configuration): Remove periods

---

.github/workflows/docs.yml
.github/workflows/release.yml

ci: bump actions/checkout from v1 to v2

---

docs/deployment.md

Sadly, probot-serverless-now a) no longer works and b) was archived today
See https://github.com/tibdex/probot-serverless-now/commit/5552cfa45ed4ac0f11e9229d57c9089cb8a55c35 for more information
Corssref to https://github.com/tibdex/probot-serverless-now/issues/12, too
-----
[View rendered docs/deployment.md](https://github.com/timbru31/probot/blob/patch-1/docs/deployment.md)

docs: remove Vercel Now

---

.github/workflows/ci.yml
package-lock.json
package.json
src/context.ts
test/integration/webhook.test.ts

This fixes the docs building and publishing by bumping the TypeScript dependency from 3.7.5 to 3.9.3. This is required by `typedoc` >= 0.17.0 (see https://github.com/TypeStrong/typedoc/issues/1257).
It also fixes two trailing spaces and the integration test data import in order to get `npm test` green again (this test was flaky on my machine as well as in the CI). Furthermore, it changes the `macOS` GitHub Actions identifier to `macos-latest` in order to run the tests at all.

ci: fixes docs publishing by upgrading typescript dependency

---

.github/workflows/docs.yml
script/publish-docs

This should (finally) fix the docs pushing - due to #1230  the deployment broke because the `actions/checkout@2` does not fetch the tags per default anymore. 
I've updated the CI script to fetch the last 20 commits and the tags and updates the `VERSION` detection a bit (the `--match` would still require the full history) - to detect such issues earlier I've added a simple `echo` of the variables.

ci: updates docs push action by fetching tags & setting the correct tag

---

package.json

These typings are used and reexported by probot and therefore are
dependencies which need to be installed by users as well.
Relates to #759

fix(typescript): add runtime types as dependencies

---

src/index.ts
test/index.test.ts

@NikhilM98 opened a PR (#784) in 2018 and it had no activity since Feb 2019. All of the credit goes to @NikhilM98, I just added the missing test
closes #784

fix: Port in use error handling (#767)

---

docs/testing.md
src/application.ts
src/index.ts

when set to `{ enabled: fales }`, all throttling from the `throttling` and
`retry` Octokit plugins will be disabled. This is very useful when testing
closes #1271
-----
[View rendered docs/testing.md](https://github.com/probot/probot/blob/disable-throttling/docs/testing.md)

feat: `throttleOptions` for Probot constructor

---

package-lock.json
package.json
src/context.ts
src/serializers.ts

closes #1080
BREAKING CHANGE: `registry_package` event was renamed to `package`

feat: update to `@octokit/webhooks` v7

---

src/context.ts
test/context.test.ts

closes #917
closes #926
closes #1168
BREAKING CHANGE: `context.issue()` now returns `.issue_number` instead of `.number`

feat: `context.pullRequest()`

---

package.json

Suggested by @gr2m via https://github.com/probot/probot/issues/1319

fix: remove broken `start` script from package.json

---

src/index.ts
test/index.test.ts

I'm new to TypeScript so please forgive in advance any silly mistake here.
I believe it's valuable to know which version of Probot a Probot-application instance is based on, AFAIK the only way at the moment is to inspect `node_modules/probot/package.json` but I believe at least logging it at startup is a good thing.
Probably is also a good idea to expose that via `GET /version`, together with the actual application version, something like this maybe?
```json
{
"appVersion": "0.1.2",
"probotVersion": "3.4.5"
}
```

feat: log Probot version at startup

---

src/index.ts
src/types.ts
test/index.test.ts

reproduces and fixes https://github.com/probot/probot/discussions/1323\#discussioncomment-59322 /cc @shaftoe

fix: `app.auth(installationId)` returns `octokit` instance with all required installation authentication settings

---

bin/probot-receive.js

via Slack ([message](https://probot-talk.slack.com/archives/C6S4FC8AF/p1599143823146400))
> hello i'm unable simulate receiving webhooks with probot v10\
> whenever i run this command\
> `node_modules/.bin/probot receive -e <event-name> -p <path-to-fixture> <path-to-app>`\
>  with either the issue.opened.json fixture or my own i get this error  `Error: Cannot find module '../lib/private-key'`  in `node_modules/probot/bin/probot-receive.js`\
> this is the npm script i ran `"test:issue": "node_modules/.bin/probot receive -e issue -p test/fixtures/issues.opened.json ./lib"`\
> also i didn't face such issue with v9
`probot receive` is currently not covered by tests.

fix: merge Octokit throttle options deeply

---

src/index.ts
test/deprecations.test.ts

Signed-off-by: Frankzhaopku <syzhao1988@126.com>
Remove redundant `instead` in the warning message.

fix: remove redundant string in deprecation warning

---

src/index.ts

You might not always have access to the host running Probot but in most of the cases (including Heroku and serverless) you can read (startup) logs, I think it's valuable to log interesting runtime information like this at startup

feat: log Node.js version at startup

---

src/apps/setup.ts
test/apps/__snapshots__/setup.test.ts.snap
test/apps/setup.test.ts
views/import.hbs
views/setup.hbs

This will close #1149
1. Probot does not support webhooks without secrets, right?
2. Is there anything else that should be set (right now APP_ID, PRIVATE_KEY and  WEBHOOK_SECRET are set)
3. Is there a way to overwrite the webhook url using an API that I did not find?

feat(setup): support registration using an existing GitHub app

---

src/octokit/get-probot-octokit-with-defaults.ts
test/index.test.ts

fixes a bug that surfaced in https://github.com/wip/app/pull/251

fix: do not overwrite `options.throttle` passed to `{Octokit: ProbotOctokit.defaults(options)}

---

package-lock.json
src/context.ts
src/octokit/get-webhooks.ts
src/types.ts
test/index.test.ts

Several TypeScript errors occur due to the changes in https://github.com/octokit/webhooks.js/pull/292
To resolve
1. `@octokit/webhooks` needs to export `EventTypesPayload`. We can derive the removed `EventNames` type from `keyof EventTypesPayload`
2. We now have to manually pass a type to `new Webhooks`, see https://github.com/octokit/webhooks.js/pull/292/files#r499279178, in order for the type of `Context` to be set correctly
@ankeetmaini could you help with this?

 fix(typescript): adapt for latest `@octokit/webhooks`

---

src/octokit/get-webhooks.ts
src/types.ts

follow up to https://github.com/probot/probot/pull/1374/files\#r501871740
@ankeetmaini I tested it locally with `create-probot-app` and it resolved the problem. But maybe I'm misisng something why you added the `Pick<...>` there?

fix(types): set correct type for `context` passed to event handler

---

package-lock.json
package.json
src/context.ts
test/index.test.ts

Follow up of https://github.com/octokit/webhooks.js/pull/321

refactor: use `WebhookEvents` export instead of an internal one.

---

package-lock.json
package.json
src/octokit/get-webhooks.ts

I've been seeing [this deprecation warning](https://github.com/octokit/webhooks.js/blob/master/src/event-handler/on.ts#L34-L41) (looks like it was introduced in `v7.15.0`) when running my Probot app or running unit tests against it. Hopefully this removes it!
**Disclaimer:** I haven't tested this fix.

fix: Use webhooks.onError() instead of deprecated webhooks.on("error", ...)

---

.github/ISSUE_TEMPLATE/Bug_report.md
README.md
README.pt-br.md
docs/extensions.md
docs/github-api.md
docs/hello-world.md
docs/http.md
docs/logging.md
docs/pagination.md
docs/persistence.md
docs/webhooks.md
src/application.ts
src/apps/default.ts
src/apps/setup.ts
src/auth.ts
src/index.ts
src/load.ts
src/route.ts
src/types.ts
test/application.test.ts
test/deprecations.test.ts
test/e2e/hello-world.js
test/index.test.ts
test/webhook-event-check.test.ts

part of #1398, in preparation of separating server APIs from the `app` instance. We will pass a separate `({ app, router }) => {}` argument in future
-----
[View rendered .github/ISSUE_TEMPLATE/Bug_report.md](https://github.com/probot/probot/blob/1398/deprecate-app-fn/.github/ISSUE_TEMPLATE/Bug_report.md)
[View rendered README.md](https://github.com/probot/probot/blob/1398/deprecate-app-fn/README.md)
[View rendered README.pt-br.md](https://github.com/probot/probot/blob/1398/deprecate-app-fn/README.pt-br.md)
[View rendered docs/extensions.md](https://github.com/probot/probot/blob/1398/deprecate-app-fn/docs/extensions.md)
[View rendered docs/github-api.md](https://github.com/probot/probot/blob/1398/deprecate-app-fn/docs/github-api.md)
[View rendered …

feat: `(app) => {}` is now `({ app }) => {}`

---

src/index.ts
test/index.test.ts

feat: `probot.on()` / `probot.receive()` / `probot.auth()`

---

src/application.ts
src/apps/default.ts
src/apps/setup.ts
src/index.ts
src/load.ts
src/types.ts
test/application.test.ts
test/deprecations.test.ts
test/index.test.ts

feat: deprecate `{ Application }` export. Use `{ Probot }` instead, it has the same APIs now.

---

src/probot.ts

fix: remove `GHE_HOST` deprecation message when using `probot run` cli

---

src/load.ts
test/deprecations.test.ts

fix: `app.route()` with `(app) => {}` app function

---

docs/serverless-deployment.md
src/create-node-middleware.ts
src/create-probot.ts
src/get-options.ts
src/index.ts
src/types.ts
test/create-node-middleware.test.ts
test/create-probot.test.ts
test/deprecations.test.ts

addresses https://github.com/probot/probot/issues/1286#issuecomment-739597798
With this change, a `probot` instance is created outside of the request handler method, which makes it reusable across multiple requsets, see https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/
-----
[View rendered docs/serverless-deployment.md](https://github.com/probot/probot/blob/deprecate-get-options/docs/serverless-deployment.md)

feat: `createProbot()`, `createNodeMiddleware(app, { probot })`. Deprecates `getOptions`, `createNodeMiddleware(app, { Probot })`

---

docs/webhooks.md

Hi maintainers!! 👋🏽 
This is just a small typo in the [webhooks documentation](https://probot.github.io/docs/webhooks/).
-----
[View rendered docs/webhooks.md](https://github.com/homeles/probot/blob/master/docs/webhooks.md)

docs(webhooks): typo in usage example

---

.github/ISSUE_TEMPLATE/Bug_report.md
README.md
README.pt-br.md
docs/extensions.md
docs/github-api.md
docs/hello-world.md
docs/http.md
docs/logging.md
docs/pagination.md
docs/persistence.md
docs/serverless-deployment.md
docs/webhooks.md
src/application.ts
src/auth.ts
src/load.ts
src/probot.ts
src/run.ts
src/types.ts
test/create-node-middleware.test.ts
test/deprecations.test.ts
test/e2e/hello-world.js
test/fixtures/example.js
test/server.test.ts
test/webhook-event-check.test.ts

see discussion at https://github.com/probot/probot/issues/1286\#issuecomment-744094299
Once this is merged, the `beta` release needs to be adjusted accordingly. It will be a breaking change between beta.3 and beta.4, I will not introduce a deprecation during beta
-----
[View rendered .github/ISSUE_TEMPLATE/Bug_report.md](https://github.com/probot/probot/blob/1438/revert-app-function-change/.github/ISSUE_TEMPLATE/Bug_report.md)
[View rendered README.md](https://github.com/probot/probot/blob/1438/revert-app-function-change/README.md)
[View rendered README.pt-br.md](https://github.com/probot/probot/blob/1438/revert-app-function-change/README.pt-br.md)
[View rendered docs/extensions.md](https://github.com/probot/probot/blob/1438/revert-app-function-change/docs/extensions.md)
[View rendered …

feat: un-deprecate `(app) => {}`. Deprecate `({ app, getRouter }) => {}` in favor of `(app, { getRouter }) => {}`

---

docs/extensions.md

I won't have time to support the extension in the future, so it's best to remove it from the Probot docs.
-----
[View rendered docs/extensions.md](https://github.com/dessant/probot/blob/patch-1/docs/extensions.md)

docs: remove probot-messages extension

---

src/bin/probot-receive.ts
src/helpers/resolve-app-function.ts
src/run.ts
test/resolver.test.ts

There had been a fix previously #1448, to load transpiled app functions
for `probot run`.
This commit replaces the custom check for `.default` and `.__esModule`
properties with a dynamic import, which TypeScript compiles to a
`require` call that is capable of handling both, commonJS and ESM, as
long as `esModuleInterop` is set to `true` in probot's root
`tsconfig.json`.
Since a dynamic import is async, I had to wrap the `probot receive` CLI
in an async function.
*Tipp:* Add `?w=1` to the diff view, to ignore whitespace changes:
https://github.com/probot/probot/pull/1457/files?w=1

fix: correctly import (transpiled) app function for run and receive

---

src/context.ts

- Clarify that pullRequest method returns an object with pull_number as a
param instead of an issue_number param.

docs: Fix pullRequest method docstring

---

src/helpers/get-error-handler.ts
test/__snapshots__/probot.test.ts.snap

The invalid pem message can appear, when the pem is corrent but only the app_id is wrong. This could come from an reinstalltion of the app or migrating from local to prod.

Enhance error message on wrong pem error

---

package-lock.json
package.json

The new types introduced in `@octokit/webhooks@7.22.0`, are incompatible with the current codebase. This will prevent users from getting anything newer than the pinned version in order to avoid type errors for end-users

fix(deps): pin version of @octokit/webhooks

---

docs/deployment.md

The _Serverless_ section had a broken link since the specific _Serverless_ page was removed [here](https://github.com/probot/probot/commit/c612fc903de291a620867713c7fc774242937795#). Furthermore, it feels redundant to keep this section now that we have a section about _Serverless Functions_ in this _Deployment_ page.
-----
[View rendered docs/deployment.md](https://github.com/imwiss/probot/blob/patch-1/docs/deployment.md)

Updating the Deployments page

---

docs/deployment.md

The given url results in a 404 because it was misspelled.
-----
[View rendered docs/deployment.md](https://github.com/zkoppert/probot/blob/patch-1/docs/deployment.md)

Fix url to Probot repo

---

docs/development.md

Under the section, ["Use Probot"](https://probot.github.io/docs/development/#use-codeprobotcode), the first sentence is missing the word, `use`. This PR adds the word to the sentence.
-----
[View rendered docs/development.md](https://github.com/jaylenw/probot/blob/master/docs/development.md)

docs: update sentence to include the word "use"

---

docs/development.md

Hey everybody 👋🏼 
The ` punctuation in header texts are breaking anchor links. The anchor links are being rendered with a
code prefix and suffix by "probot/probot.github.io", Eg. #use-coderuncode.
I've removed the ` punctuations from the header texts to fix this.
Seeing that this PR just touches docs, how do you all want to proceed with failing test?
-----
[View rendered docs/development.md](https://github.com/froi/probot/blob/remove-punctuation-from-headers/docs/development.md)

Remove grave accents (`) from header texts

---

views/import.hbs
views/probot.hbs
views/setup.hbs
views/success.hbs

This adds a dark mode to all builtin pages.
Dark mode gets automatically enabled depending on the color scheme set in the browser/operating system-
This is a follow-up for #1508, which updated primer.css to a version that supports dark mode.
Here's how it looks on the setup page:

feat: Add dark mode to builtin pages

---

src/run.ts

Some part already have an await some not. This should make it behave the same if the app has an async entry point.
Please let me know what you think.
One test fails for me (end-to-end-tests › hello-world app) but it does that even without my change.

Add await to probot and server load

---

src/probot.ts

As discussed in https://github.com/probot/probot/pull/1481#discussion_r622396089 it isn't possible to use this event any longer with further versions of `@octokit/webhooks`.
This logs a deprecation warning if users end up using it

feat: deprecate usage of the "*" event name

---

src/apps/setup.ts
src/manifest-creation.ts
test/apps/__snapshots__/setup.test.ts.snap
test/apps/setup.test.ts

This adds the missing env settings:
- GITHUB_CLIENT_ID
- GITHUB_CLIENT_SECRET
This also skips creating the WEBHOOK_PROXY_URL when the host is defined and smee is not needed. This way the setup process through the web page '/probot/setup' will work without using smee.

fix(setup): do not enter setup mode if `HOST` environment variable is set

---

src/apps/setup.ts

Using the host variable did create side effect for some docker container. This should solve that.
Is there a good way to test a lib in typescript without publishing them?

fix: skipp smee setup without side effects of host variable

---

src/octokit/get-probot-octokit-with-defaults.ts
test/probot.test.ts

fix: support setting `baseUrl` on Octokit constructor instead of Probot constructor

---

docs/development.md

When automatically configuring the GitHub App, documentation says to trigger an event and then restart. The event won't be received unless you have restarted already as `smee` isn't listening yet. 
-----
[View rendered docs/development.md](https://github.com/helaili/probot/blob/patch-1/docs/development.md)

docs(development): Need to restart once before receiving

---

package-lock.json
package.json
src/context.ts
src/create-node-middleware.ts
src/helpers/get-error-handler.ts
src/index.ts
src/octokit/get-webhooks.ts
src/octokit/octokit-plugin-probot-request-logging.ts
src/octokit/octokit-webhooks-transform.ts
src/probot.ts
src/server/server.ts
src/types.ts
test/context.test.ts
test/create-node-middleware.test.ts
test/e2e/e2e.test.ts
test/e2e/hello-world.js
test/probot-octokit.test.ts
test/probot.test.ts
test/run.test.ts
test/server.test.ts
test/types/probot.test-d.ts

follow up to https://github.com/probot/probot/pull/1481

feat: update `@octokit/webhooks` to v9

---

package-lock.json
package.json
src/context.ts
src/create-node-middleware.ts
src/helpers/get-error-handler.ts
src/index.ts
src/octokit/get-webhooks.ts
src/octokit/octokit-plugin-probot-request-logging.ts
src/octokit/octokit-webhooks-transform.ts
src/probot.ts
src/server/server.ts
src/types.ts
test/context.test.ts
test/create-node-middleware.test.ts
test/e2e/e2e.test.ts
test/e2e/hello-world.js
test/probot-octokit.test.ts
test/probot.test.ts
test/run.test.ts
test/server.test.ts
test/types/probot.test-d.ts

BREAKING CHANGE: remove '*' event
BREAKING CHANGE: app.webhooks.middleware has been removed in `@octokit/webhooks` v9
BREAKING CHANGE: removes the `webhookPath` option on `new Probot({})` for the webhooks middleware
Co-authored-by: wolfy1339 <webmaster@wolfy1339.com>

feat: update `@octokit/webhooks` to v9 (#1559)

---

.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test.yml

Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

ci(workflow): add cache to workflows using actions/setup-node

---

docs/hello-world.md

Currently, the link to `Developing an App` on https://probot.github.io/docs/hello-world/ points to https://probot.github.io/docs/hello-world/development.md which does not exist. This PR fixes that.
-----
[View rendered docs/hello-world.md](https://github.com/tnorthcutt/probot/blob/patch-1/docs/hello-world.md)

docs: Correct wrong link to `Developing an App` page

---

.github/workflows/docs.yml

close #1327
For a long time now tags are created using a GItHub Action using `secrets.GITHUB_TOKEN`, so other actions don't act on it anyway

ci(docs): do not update docs when tags are created

---

docs/development.md

There is a broken image link for "Screenshot of Probot's setup wizzard" in `docs/development.md` (also wizard is misspelled). This corrects the link and the misspelling.
-----
[View rendered docs/development.md](https://github.com/lisadean/probot/blob/fix-broken-image-link/docs/development.md)

docs: fix broken image link in development doc

---

docs/deployment.md
docs/development.md

This PR adds the missing `webhooksPath` option to the docs for `createNodeMiddleware`
fixes: #1587 
-----
[View rendered docs/development.md](https://github.com/maximousblk/probot/blob/patch-1/docs/development.md)

docs: add `webhooksPath` option for `createNodeMiddleware`

---

src/context.ts

This will give typescript the correct return type.
My ts compiler complains about the any type, this should fix it.
Only question would be if the context type does not support some of the properties the correct type would be undefined.
This would mask the error.
The first commit is the easy solution, the second uses conditional types to detect that problem.
Let me know what you think.
Should I add export to the types?

fix: added definite type so that caller does not get warnings

---

package.json
src/context.ts
test/fixtures/webhook/push.json

This also should fix the prettier config for windows user.
Please let me know if you think there are any problems.

refactor: remove fallback to `.owner.name` when `.owner.login` is not set. `.owner.login` is always set

---

docs/development.md

The currently documented example
```
function myProbotApp(app) {
const octokit = new ProbotOctokit({
// any options you'd pass to Octokit
auth: "token <myToken>",
// and a logger
log: app.log.child({ name: "my-octokit" }),
});
}
```
does not work. It will return an error because of missing auth.
This PR modifies the example to show the currently supported way for token auth
-----
[View rendered docs/development.md](https://github.com/chris-schra/probot/blob/patch-1/docs/development.md)

docs(development): fix `ProbotOctokit` usage example

---

.typedoc.json
package-lock.json
package.json

`hbs` depends on `handlebars` which had a vulnerability of critical severity
bumped `typedocs` as it was not compatible with the typescript version defined in dev dependencies.
package-lock had a version reference to ansi-regex v4.0.1 which had a vulnerability of moderate severity.

build(package): bump package and package-lock

---

README.md

`context.log.error(error)` wouldn't work here since context is not exposed
-----
[View rendered README.md](https://github.com/atymchuk/probot/blob/patch-1/README.md)

docs: wrong log call in `onError` method

---

docs/http.md

Fixes bad link to `https://` protocol on `localhost`.
-----
[View rendered docs/http.md](https://github.com/nickofthyme/probot/blob/patch-1/docs/http.md)

docs: fix localhost link protocol

---

src/octokit/get-probot-octokit-with-defaults.ts
test/create-probot.test.ts

This should fix the logging in the default ocotkit instance from issue #1673

fix: logging of first octokit instance is not set

---

package-lock.json
package.json
src/bin/probot.ts

It's better to catch outdated dependencies before deployment, with tools such as dependabot, instead of only finding about it when you're about to run the application.
The motivation for having update-notifier isn't strong as per https://github.com/probot/probot/issues/1102#issuecomment-570598406 and it pulls in needless dependencies as showcased in https://github.com/probot/probot/issues/1703, therefore it's better to remove it.
close #1703

fix: remove update-notifier

---

docs/deployment.md

Heroku default deployment branch is now named "main" not "master"
-----
[View rendered docs/deployment.md](https://github.com/borgmanJeremy/probot/blob/patch-1/docs/deployment.md)

docs(deployment): Update Heroku branch name

---

src/bin/probot-receive.ts

When testing probots on a self-hosted enterprise github instance, the command `probot receive -e push -p test/test-push.json ./index.js` does not recognize the GHE_HOST present in the .env file and does not allow the baseUrl to be modified in the receive arguments.
This change allows the GHE_HOST value in the .env file to be recognized and also allows the host to be modified in the arguments of the command.  Basically a copy and paste from read-cli-options.ts.
fixes #1556
fixes #1333

fix(receive): `--base-url` option and `GHE_HOST`

---

src/bin/probot-receive.ts
src/probot.ts

The command `probot receive` fails to work when:
1. The Probot appFn is asynchronous
2. The Probot appFn requires `getRouter`
The command `probot run` works fine though with the same Probot appFn.
This attempts to add support for these sorts of Probot apps when calling `probot receive`.

fix: Make `probot receive` support complex Probot apps

---

src/server/logging-middleware.ts
src/server/server.ts
src/types.ts
test/server/logging-middleware.test.ts

Enable to receive pino-http option to logging-middleware.
For example, even if normally want to handle all access logs, may need to exclude some endpoints. (e.g. health check endpoint). And, It may also be useful for developers to be able to specify other options.

feat(server): add logging options

---

package-lock.json
package.json
src/bin/probot.ts
src/helpers/is-supported-node-version.ts
test/bin/is-supported-node-version.test.ts

We dont need semver. We maybe change the engines field every 6 month. For that we can manually write a function, which checks if the node version is correct. A unit test ensures that the tests fail if the engines field is changed but the validate function is not updated.

fix(deps): -semver

---

.github/workflows/codeql.yml

This sets up CodeQL to automatically detect possible security problems.

ci(security): Set up code scanning

---

src/auth.ts

I am currently trying to improve the test coverage. It seems that we dont use the log parameter so it is a dead branch.

refactor: remove `log` argument from auth.ts to improve test coverage

---

src/helpers/webhook-proxy.ts
src/manifest-creation.ts
src/server/server.ts
test/webhook-proxy.test.ts

I assume that using require in an esm environment could break.

fix: use `import()` instead of `require` to import `smee-client`

---

src/bin/probot-receive.ts
src/bin/probot.ts
src/run.ts

This and #1890 and #1891 will remove all require calls.

refactor: avoid require for `dotenv.config()`

---

src/bin/probot-receive.ts

I guess you could actually load arbitrary code into probot receive cli command.

fix: use `readFileSync` and `JSON.parse` instead of `require` in probot-receive

---

src/octokit/probot-octokit.ts
test/probot-octokit.test.ts

This PR reveals, that we have some typings issue with the throttling plugin. We are setting some default values, e.g. `onRateLimit`, so theoretically they are not mandatory. But because we dont reflect this in the ProbotOctokit constructor, they are still mandatory.

test: 100% probot octokit

---

.github/workflows/test.yml
package.json

Because of #1901 I think it would be nicer to split linting and testing inthe workflows. Should also slightly improve test runs on the CI, because we only need to run the linting once.

ci: split lint job from test matrix

---

example/node-middleware.cjs
src/create-node-middleware.ts

adding example as a potential approach to add benchmarks.
This is also to show the performance difference between latest 12 and our 13 beta branch:
v12
```sh
Running 10s test @ http://127.0.0.1:3000/
10 connections
┌─────────┬───────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
├─────────┼───────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
│ Latency │ 18 ms │ 24 ms │ 50 ms │ 56 ms │ 26.16 ms │ 9.89 ms │ 152 ms │
└─────────┴───────┴───────┴───────┴───────┴──────────┴─────────┴────────┘
┌───────────┬───────┬───────┬─────────┬─────────┬─────────┬─────────┬───────┐
│ Stat      │ 1%    │ 2.5%  │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min   │ …
```

chore: add example for benchmarks

---

.github/workflows/test.yml

Because build is run by pretest automatically, we're currently building twice.

ci: Speed up CI by skipping build

---

src/server/server.ts

fix: derive `Server` log from `Probot` log

---

.github/workflows/test.yml

Assure 'test' Check Run is always executed and `fails`/`succeeds` accordingly to the results of its dependency jobs.
- Example commit with all tests passing ✅: https://github.com/octokit/auth-oauth-device.js/commit/c4a2c50e7eb30baa6b3fb54c75e3c31429c591ed
- Example commit with tests failing 🔴: octokit/auth-oauth-device.js@8d93278aa268be6706f97c973a17d3d05cbac53f
---
When using `job.needs`, [by default only runs when the dependency jobs succeed](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds). If one or more of them fail, the dependent job is **skipped**

ci(workflow): fix `test` workflow to assure it is not skipped if dependant jobs fails

---

src/types.ts

This documents the different reasons for the `SimplifiedObject` type, starting from the `Omit`, and finishing with the type itself

chore: add comment to `SimplifiedObject`

---

src/apps/default.ts
src/apps/setup.ts
src/bin/probot-receive.ts
src/bin/probot.ts
src/context.ts
src/helpers/load-package-json.ts
src/manifest-creation.ts
src/server/logging-middleware.ts
src/server/server.ts
src/types.ts
test/apps/default.test.ts
test/apps/setup.test.ts
test/bin/is-supported-node-version.test.ts
test/context.test.ts
test/create-node-middleware.test.ts
test/helpers/load-package-json.test.ts
test/integration/integration-smee.test.ts
test/manifest-creation.test.ts
test/probot.test.ts
test/run.test.ts
test/server.test.ts
test/server/logging-middleware.test.ts
test/webhook-proxy.test.ts

I was playing around with deno. It does not like if built ins are not loaded with node prefix and json files need to be imported with assert json.
Lets see if the ci passes.

fix: add node prefix for builtin modules

---

docs/simulating-webhooks.md

docs: formatting typo in simulating-webhooks.md

---

src/helpers/get-log.ts
src/helpers/rebind-log.ts
src/probot.ts
src/server/server.ts

@gr2m 
@wolfy1339 
This PR adds a function to rebind the log instance to avoid the reported potential breaking change.
Would like to add a unit test which needs @octokit/plugin-request-log plugin and checks if it works. 
This would be my approach, so you can say if you like it or not.

fix: bind log

---

.typedoc.json

Seems like listInvalidSymbolLinks is deprecated or so, removed it

chore:  repair typedoc

---

test/e2e/e2e.test.ts
test/e2e/hello-world.mjs

Previously, the E2E test only tested a CJS app. This test ensures compatibility with ESM apps.

test: Ensure we can run both ESM and CJS

---

.github/workflows/release.yml
package.json

This adds a cryptographic signature to NPM uploads to show that a upload was done by GitHub actions and not somewhere else. Such a feature should help detect malicious uploads to NPM. This feature could be extended to other repositories too.

feat(security): Configure provenance

---

src/octokit/get-webhooks.ts
test/probot.test.ts

Current behavior:
```js
const probot = new Probot({ log: myCustomLog });
probot.on("my_custom_event", handler);
// logs with console, not with `myCustomLog`
```
With this pull request, `myCustomLog` will be passed to webhooks and the warning will be logged using the passed logger instead of native `console`

fix(probot): passes logger to webhooks

---

src/context.ts
test/context.test.ts

Implements this useful feature from `@octokit/app` 
https://github.com/octokit/app.js/blob/7b65f978368f714fb85b7df4a2dd696de203c6a2/src/webhooks.ts#L52-L60

feat: set `x-github-delivery` header to `event.id` for all requests sent from `context.octokit` in event handlers

---

docs/testing.md

Hi there,
There is currently an issue with `Octokit: ProbotOctokit.defaults()` regarding throttling, which I've opened up an [issue](https://github.com/probot/probot/issues/2039#issue-2368070197) for, issue number #2039. It describes the problem in great detail with valid proofs and a solution.
This PR updates the documentation's 'Testing' section/tab with the solution (or rather hotfix) to prevent developers from struggling in testing environments. Personally it took me couple of hours before I found a solution to it. Hopefully it helps other people from wasting time as well, until a proper solution is conducted.
I've update the code section with strong type def which could be overkill, because it requires an additional import on line 13, we can remove the type definitions if not needed. …

docs(testing): use `ProbotOctokit.defaults()` callback

---

.typedoc/typedoc_ga.mjs
package.json

Typedoc recently removed the corresponding option. This makes builds work again by "recovering" that code as a plugin.

fix(docs): Re-enable Google Analytics

---

package-lock.json
package.json
src/helpers/webhook-proxy.ts
src/server/server.ts
test/webhook-proxy.test.ts

We dont need the dependency, as we only need it for the types of EventSource. smee-client is returning an EventSource instance. Also we have already EventSource definitions provided by typescript ;).

fix: remove eventsource dependency

---

src/helpers/get-log.ts

while testing if we can use esm, it showed that we missed to import with an explicit filename

chore: explicit filename import

---

src/context.ts

Fixes #1968
> error TS2590: Expression produces a union type that is too complex to represent.
The solution was taken from https://github.com/ubiquity/ubiquibot-kernel/pull/52
See https://github.com/probot/probot/issues/1680
See https://github.com/probot/probot/discussions/1966

fix(types): avoid TS2590 errors in `Context`

---

package-lock.json
package.json

See https://github.com/isaacs/node-lru-cache/issues/355
The package author is unwilling to backport the proper fix to the previous version.
Blocked by https://github.com/octokit/auth-app.js/pull/651

fix(deps): use fork of lru-cache to fix type issues

---

src/auth.ts
src/octokit/get-authenticated-octokit.ts

The Probot interface already provides a second parameter to [`Probot.auth`](https://github.com/probot/probot/blob/master/src/probot.ts#L45) function, however unused by the implementation. 
This PR implements this interface fully, so provided `log` (if provided) will be used by created Octokit instance instead of default logger. 
This can be useful in case when we need to add more fields to the logger to have better separation of logs, eg. based on event ID or PR number.

feat: allow custom logger for Octokit instances

---

package-lock.json
package.json
src/octokit/get-probot-octokit-with-defaults.ts
src/probot.ts
src/types.ts

This PR is corresponding to https://github.com/octokit/auth-app.js/pull/654 and replaces lru-cache with toad-cache.
toad-cache is developed by @kibertoad
We use it in fastify and have good results with it. Also it is possible to reach to kibertoad and get things merged if necessary.

replace lru-cache with toad-cache

---

src/helpers/rebind-log.ts
src/octokit/get-authenticated-octokit.ts
src/probot.ts

Sometimes the logger would be unbound, and would result in error messages.
Fixes #2116

fix: ensure that the logger is always bound 

---

docs/deployment.md
docs/development.md
example/node-middleware.cjs
src/create-node-middleware.ts

I came accross the following two issues with `createNodeMiddleware`: First, it was unclear that the returned function is a middleware and can be composed with other middlewares. Second, when used as suggested in the examples, unhandled requests would stall instead of returning a 404.

docs: update documentation for correct middleware usage

---

src/apps/setup.ts
src/context.ts
src/run.ts
test/apps/setup.test.ts
test/run.test.ts

Reduce some `// @ts-expect-error` and `// @ts-ignore` instructions in the ` /src` folder.  Especially the access to the internal state of the Probot Instance in setup.ts was always strange, especially since the state property was declared as private. Maybe someday we want to use real private fields by prefixing them with `#` and then it would not work... :D

chore: reduce ts-instructions

---

src/bin/probot.ts
src/helpers/detect-runtime.ts
src/helpers/is-supported-node-version.ts
src/helpers/is-supported-runtime.ts
test/bin/detect-runtime.test.ts
test/bin/is-supported-node-version.test.ts
test/webhook-proxy.test.ts

I am continously trying if we can improve the compatibility with bun and deno.
bun is not implementing the use of getaddrinfo so the unit tests fail completely. 
deno is throwing anyhow alot of typing issues.
With this, the tests somewhat run in bun (but still fail).

implement detectRuntime and change is-SupportedNodeVersion to isSupportedRuntime

---

src/context.ts
src/octokit/probot-octokit.ts
test/e2e/hello-world.cjs
test/e2e/hello-world.mjs
test/probot-octokit.test.ts
test/probot.test.ts

BREAKING CHANGE: Remove legacy REST enpoint method access. Users will now have to use the `octokit.rest.*` methods

feat: renove legacy REST endpoint method access

---

package-lock.json
package.json
src/bin/probot.ts
src/helpers/is-supported-runtime.ts
test/bin/is-supported-runtime.test.ts

BREAKING CHANGE: Bump minimum required Node version to 20.18.1 to match undici v7

fix(deps): bump smee-client to v4

---

test/probot.test.ts

We should not overwrite the log methods in tests, as we have potentially deferred instantiation of  the pino logger

test: avoid overwriting log methods in tests

---

package-lock.json
package.json
src/helpers/webhook-proxy.ts
src/manifest-creation.ts
src/octokit/get-octokit-throttle-options.ts
src/octokit/get-probot-octokit-with-defaults.ts
src/probot.ts
test/npx-import.test.ts
test/probot.test.ts
test/smee-client-npx-import.test.ts

As we have now the initialization async, we can dynamically load ioredis and smee-client when running probot with npx.
Needs that we agree on publishing @probot/npx-import
we would need to make ioredis and smee-client to be dev dependencies

feat: use npx-probot-light for smee-client and ioredis

---

docs/deployment.md

This pull request updates the deployment documentation for Probot to include instructions for deploying on Render and clarifies the Webhook URL setup for Heroku. These changes enhance the documentation by providing additional deployment options and improving clarity.
* **Render Deployment Instructions**:
- Added a new section in `docs/deployment.md` detailing how to deploy a Probot app on Render, including steps for creating a web service, setting environment variables, and deploying the app.
* **Heroku Webhook URL Clarification**:
- Updated the example Webhook URL for Heroku deployments to include the default webhook path (`/api/github/webhooks`).
- The change in Probot v13's default webhook path has also been reflected in the documentation.
- …

docs: add Render deployment instructions to deployment guide
